In [409]:
import pandas as pd
import numpy as np

In [410]:
df = pd.read_csv('../Data Gathering/smartphones.csv')

In [411]:
df.head()

,Name,Price,Spec Score,SIM,Processor,RAM,Battery,Display,Camera,Memory Card,OS
0,Vivo V80 5G,"₹62,999",84,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 7 Gen4, Octa Core, 2.8 GHz Processor","8 GB RAM, 128 GB inbuilt",7200 mAh Battery with 90W Fast Charging,"6.59 inches, 1260 x 2750 px, 144 Hz Display wi...",50 MP + 50 MP + 8 MP Triple Rear & 50 MP Front...,Memory Card Not Supported,Android v17
1,Samsung Galaxy S25 Ultra,"₹99,999",92,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite for Galaxy, Octa Core, 4.47...","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 45W Fast Charging,"6.9 inches, 1440 x 3120 px, 120 Hz Display wit...",200 MP Quad Rear & 12 MP Front Camera,Memory Card Not Supported,Android v15
2,Samsung Galaxy S23 5G,"₹49,999",74,"Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi","Snapdragon 8 Gen 2, Octa Core, 3.36 GHz Processor","8 GB RAM, 128 GB inbuilt",3900 mAh Battery with 25W Fast Charging,"6.1 inches, 1080 x 2340 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 12 MP Fron...,Android v13,No FM Radio
3,Motorola Edge 70 Fusion,"₹29,299",70,"Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi","Snapdragon 7s Gen4, Octa Core, 2.7 GHz Processor","8 GB RAM, 128 GB inbuilt",7000 mAh Battery with 68W Fast Charging,"6.8 inches, 1272 x 2772 px, 144 Hz Display wit...",50 MP + 13 MP + Dedicated 3-in-1 light sensor ...,Android v16,No FM Radio
4,OPPO K14 Plus 5G,"₹29,999",67,"Dual Sim, 5G, VoLTE, Wi-Fi, IR Blaster","Dimensity 7360 Max, Octa Core, 2.5 GHz Processor","6 GB RAM, 128 GB inbuilt",8000 mAh Battery with 45W Fast Charging,"6.78 inches, 1272 x 2772 px, 144 Hz Display wi...",50 MP + 2 MP Dual Rear & 16 MP Front Camera,Memory Card Not Supported,Android v16

In [412]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         1020 non-null   object
 1   Price        1020 non-null   object
 2   Spec Score   1020 non-null   int64
 3   SIM          1020 non-null   object
 4   Processor    1020 non-null   object
 5   RAM          1020 non-null   object
 6   Battery      1020 non-null   object
 7   Display      1020 non-null   object
 8   Camera       1016 non-null   object
 9   Memory Card  1006 non-null   object
 10  OS           980 non-null    object
dtypes: int64(1), object(10)
memory usage: 87.8+ KB

In [413]:
df.isnull().sum()

Name            0
Price           0
Spec Score      0
SIM             0
Processor       0
RAM             0
Battery         0
Display         0
Camera          4
Memory Card    14
OS             40
dtype: int64

## Data Assessing

`NOTE :-` All ROWS NO. ARE BASED ON PHASEONE DATASET 

`Quality Issues`
 
1. **model** - some brands are written differently like OPPO in model col.
2. **price** - has unneccesary `rupees` symbol
3. **price** - has " , " between numbers
4. **row no.** - 366(Jio Bharat J1 4G)phone has missing processor value , therefore all data is mixed up of that row. there are several phones like this
                 so we drop those phones whose price is below 3400 as below that all are feature phones not smartphones. ~ roughly 80+ phones
5. `Feature Phones` - there are many feature phones `drop` them        
6. **ram** - row no.(276(Apple iPhone 16 Plus), 478(Apple iPhone 16 Plus (256GB)) 
7. **camera** - (38,107,181,292,384,389,391,421,580,583,605,616,632,665,671,681,685,686,696,704,706,713,734,743,744,769,776,789,808,809,811,820,880,881,917,934,985,,1015,1016) - `Foldable Display AND Dual Display`

`Shifted Data Rows`

1. 533(Ringme Bold S180 Air)) 
2. 854

In [414]:
camera_rows = set((38,107,181,292,384,389,391,421,580,583,605,616,632,665,671,681,685,686,696,704,706,713,734,743,744,769,776,789,808,809,811,820,857,880,881,917,934,985,1015,1016))

In [415]:
df.duplicated().sum()

np.int64(8)

In [416]:
df1 = df.copy()

In [417]:
df1.reset_index(inplace=True)

In [418]:
df1

,index,Name,Price,Spec Score,SIM,Processor,RAM,Battery,Display,Camera,Memory Card,OS
0,0,Vivo V80 5G,"₹62,999",84,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 7 Gen4, Octa Core, 2.8 GHz Processor","8 GB RAM, 128 GB inbuilt",7200 mAh Battery with 90W Fast Charging,"6.59 inches, 1260 x 2750 px, 144 Hz Display wi...",50 MP + 50 MP + 8 MP Triple Rear & 50 MP Front...,Memory Card Not Supported,Android v17
1,1,Samsung Galaxy S25 Ultra,"₹99,999",92,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite for Galaxy, Octa Core, 4.47...","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 45W Fast Charging,"6.9 inches, 1440 x 3120 px, 120 Hz Display wit...",200 MP Quad Rear & 12 MP Front Camera,Memory Card Not Supported,Android v15
2,2,Samsung Galaxy S23 5G,"₹49,999",74,"Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi","Snapdragon 8 Gen 2, Octa Core, 3.36 GHz Processor","8 GB RAM, 128 GB inbuilt",3900 mAh Battery with 25W Fast Charging,"6.1 inches, 1080 x 2340 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 12 MP Fron...,Android v13,No FM Radio
3,3,Motorola Edge 70 Fusion,"₹29,299",70,"Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi","Snapdragon 7s Gen4, Octa Core, 2.7 GHz Processor","8 GB RAM, 128 GB inbuilt",7000 mAh Battery with 68W Fast Charging,"6.8 inches, 1272 x 2772 px, 144 Hz Display wit...",50 MP + 13 MP + Dedicated 3-in-1 light sensor ...,Android v16,No FM Radio
4,4,OPPO K14 Plus 5G,"₹29,999",67,"Dual Sim, 5G, VoLTE, Wi-Fi, IR Blaster","Dimensity 7360 Max, Octa Core, 2.5 GHz Processor","6 GB RAM, 128 GB inbuilt",8000 mAh Battery with 45W Fast Charging,"6.78 inches, 1272 x 2772 px, 144 Hz Display wi...",50 MP + 2 MP Dual Rear & 16 MP Front Camera,Memory Card Not Supported,Android v16
...,...,...,...,...,...,...,...,...,...,...,...,...
1015,1015,Samsung Galaxy Z Flip 7 FE (8GB RAM + 256GB),"₹95,999",84,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Exynos 2400, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",4000 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
1016,1016,Samsung Galaxy Z Flip 7 5G (12GB RAM+512GB),"₹1,21,999",89,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Exynos 2500, Deca Core, 3.3 GHz Processor","12 GB RAM, 512 GB inbuilt",4300 mAh Battery with 25W Fast Charging,"6.9 inches, 1080 x 2520 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
1017,1017,Philips E2102,"₹1,499",6,Unisoc SC6531E,"4 MB RAM, 4 MB inbuilt",1000 mAh Battery,1.77 inches Display,0.08 MP Rear Camera,Memory Card Supported,NaN,NaN
1018,1018,Snexian Bold A26,₹899,6,Dual Sim,100 kHz Processor,"32 MB RAM, 32 MB inbuilt",850 mAh Battery,"0.66 inches, 120 x 240 px Display",No Rear Camera,Memory Card Supported,No FM Radio
1019,1019,Philips E2112,"₹1,169",9,"32 MB RAM, 32 MB inbuilt",2500 mAh Battery,1.77 inches Display,Main Rear Camera,"Memory Card Supported, upto 32 GB",NaN,NaN,NaN

In [419]:
df1 = df1.drop_duplicates(subset=['Name'])

In [420]:
df1.duplicated().sum()

np.int64(0)

In [421]:
df1['Price'] =df1['Price'].str.replace('₹', '').str.replace(',', '').astype(int)

C:\Users\HP\AppData\Local\Temp\ipykernel_11324\531981194.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Price'] =df1['Price'].str.replace('₹', '').str.replace(',', '').astype(int)

In [422]:
df1 = df1[df1['Price'] >= 3400]

In [423]:
df1[df1['Spec Score'] < 20]

,index,Name,Price,Spec Score,SIM,Processor,RAM,Battery,Display,Camera,Memory Card,OS
430,430,Nokia 2660 Flip,5199,15,"Dual Sim, 4G",No Wifi,Unisoc T107,"48 MB RAM, 128 MB inbuilt",1450 mAh Battery,"2.8 inches, 240 x 320 px Display",Dual Display,0.3 MP Rear Camera
444,444,Nokia 235 4G 2024,4099,15,"Dual Sim, 4G, VoLTE",No Wifi,"Unisoc T107, 1 GHz Processor","64 MB RAM, 128 MB inbuilt",1450 mAh Battery,"2.8 inches, 240 x 320 px Display",2 MP Rear Camera,Memory Card Supported
548,548,Jio JioPhone,3499,18,"Single Sim, 4G, VoLTE, Wi-Fi","QC8905, Dual Core, 1.2 GHz Processor","512 MB RAM, 4 GB inbuilt",2000 mAh Battery,"2.4 inches, 240 x 320 px Display",2 MP Rear & 0.3 MP Front Camera,"Memory Card Supported, upto 128 GB",Bluetooth
608,608,Nokia 3210 4G (2024),4349,14,"Dual Sim, 4G",No Wifi,"Unisoc T107, 1 GHz Processor","64 MB RAM, 128 MB inbuilt",1450 mAh Battery,"2.4 inches, 240 x 320 px Display",2 MP Rear Camera,"Memory Card Supported, upto 32 GB"
609,609,Nokia 220 4G (2024),3479,13,"Dual Sim, 4G",No Wifi,Unisoc T107,"64 MB RAM, 128 MB inbuilt",1450 mAh Battery,"2.8 inches, 240 x 320 px Display",No Rear Camera,"Memory Card Supported, upto 32 GB"
727,727,Nokia 5310 Dual Sim,3889,10,Dual Sim,"8 MB RAM, 16 MB inbuilt",1200 mAh Battery,"2.4 inches, 240 x 320 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 32 GB",Bluetooth,Browser
787,787,Nokia 6310 (2024),3739,12,Dual Sim,Unisoc 6531F,"8 MB RAM, 16 MB inbuilt",1450 mAh Battery,"2.8 inches, 240 x 320 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 32 GB",S30+
869,869,MTR M16 Pro,6600,17,"Dual Sim, 4G, Wi-Fi","Helio, 512 MHz Processor","3 GB RAM, 32 MB inbuilt",2000 mAh Battery,"4 inches, 480 x 640 px Display with Punch Hole",5 MP Rear Camera,Android v13.0,Bluetooth

In [424]:
df1.drop([430, 444, 548, 608, 609, 727, 787],inplace=True)

In [425]:
df1[df1['Spec Score'] < 20]

,index,Name,Price,Spec Score,SIM,Processor,RAM,Battery,Display,Camera,Memory Card,OS
869,869,MTR M16 Pro,6600,17,"Dual Sim, 4G, Wi-Fi","Helio, 512 MHz Processor","3 GB RAM, 32 MB inbuilt",2000 mAh Battery,"4 inches, 480 x 640 px Display with Punch Hole",5 MP Rear Camera,Android v13.0,Bluetooth

In [426]:
df1[df1['Price'] == 43900]

Empty DataFrame
Columns: [index, Name, Price, Spec Score, SIM, Processor, RAM, Battery, Display, Camera, Memory Card, OS]
Index: []

In [427]:
df1.to_csv('smartphones_cleaned_firstphase.csv', index=False)

In [428]:
temp_df = df1[df1['Name'] == 'Ringme Bold S180 Air']

In [429]:
temp_df

,index,Name,Price,Spec Score,SIM,Processor,RAM,Battery,Display,Camera,Memory Card,OS
553,553,Ringme Bold S180 Air,9999,32,"Dual Sim, 4G, VoLTE, Wi-Fi","6 GB RAM, 64 GB inbuilt",4800 mAh Battery,"6.51 inches, 1440 x 720 px Display",16 MP Rear & 8 MP Front Camera,"Memory Card Supported, upto 256 GB",Android v12,No FM Radio

In [430]:
x = temp_df.iloc[:,5:].shift(1,axis=1)

In [431]:
x

,Processor,RAM,Battery,Display,Camera,Memory Card,OS
553,None,"6 GB RAM, 64 GB inbuilt",4800 mAh Battery,"6.51 inches, 1440 x 720 px Display",16 MP Rear & 8 MP Front Camera,"Memory Card Supported, upto 256 GB",Android v12

In [432]:
df1.loc[temp_df.index,temp_df.columns[5:]] = x

In [433]:
df1[df1['index'] == 854]

,index,Name,Price,Spec Score,SIM,Processor,RAM,Battery,Display,Camera,Memory Card,OS
854,854,Peace i17 Air,9499,27,"Dual Sim, 4G, VoLTE, Wi-Fi",5000 mAh Battery,"6.56 inches, 1640 x 720 px Display",20 MP Rear & 8 MP Front Camera,"Memory Card Supported, upto 128 GB",Android v14.0,No FM Radio,Bluetooth

In [434]:
tempdf_1 = df1[df1['index'] == 854]

In [435]:
x = tempdf_1.iloc[:,5:].shift(2,axis=1)

In [436]:
x

,Processor,RAM,Battery,Display,Camera,Memory Card,OS
854,None,None,5000 mAh Battery,"6.56 inches, 1640 x 720 px Display",20 MP Rear & 8 MP Front Camera,"Memory Card Supported, upto 128 GB",Android v14.0

In [437]:
df1.loc[tempdf_1.index,tempdf_1.columns[5:]] = x

In [438]:
df1[df1['index'] == 38]

,index,Name,Price,Spec Score,SIM,Processor,RAM,Battery,Display,Camera,Memory Card,OS
38,38,Lava Virat Curve,23999,64,"Dual Sim, 5G, VoLTE, Vo5G, Wi-Fi","Dimensity 7100, Octa Core, 2.4 GHz Processor","6 GB RAM, 128 GB inbuilt",6000 mAh Battery with 45W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",Dual Display,50 MP Dual Rear & 13 MP Front Camera,Android v16

In [439]:
temp_df = df1[df1['index'].isin(camera_rows)]

In [440]:
df1.loc[temp_df.index,'Camera'] = temp_df['Memory Card']

In [441]:
df1[df1['index'].isin(camera_rows)]

,index,Name,Price,Spec Score,SIM,Processor,RAM,Battery,Display,Camera,Memory Card,OS
38,38,Lava Virat Curve,23999,64,"Dual Sim, 5G, VoLTE, Vo5G, Wi-Fi","Dimensity 7100, Octa Core, 2.4 GHz Processor","6 GB RAM, 128 GB inbuilt",6000 mAh Battery with 45W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP Dual Rear & 13 MP Front Camera,50 MP Dual Rear & 13 MP Front Camera,Android v16
107,107,Vivo X Fold 6,219999,95,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Dimensity 9500 Super Edition, Octa Core, 4.21 ...","12 GB RAM, 512 GB inbuilt",6900 mAh Battery with 80W Fast Charging,"8.02 inches, 2312 x 2504 px, 120 Hz Display wi...",200 MP + 50 MP + 50 MP Triple Rear & 20 MP Fro...,200 MP + 50 MP + 50 MP Triple Rear & 20 MP Fro...,Android v17
181,181,Apple iPhone Duo (2TB),449900,84,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20 Pro, Hexa Core Processor","12 GB RAM, 2 TB inbuilt",5800 mAh Battery with Fast Charging,"7.6 inches, 1878 x 2670 px, 120 Hz Display",48 MP + 48 MP Dual Rear & Under-display FaceTi...,48 MP + 48 MP Dual Rear & Under-display FaceTi...,Memory Card Not Supported
292,292,Samsung Galaxy Z Fold 8 Ultra,194999,98,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 For Galaxy, Octa Core...","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 45W Fast Charging,"8 inches, 2256 x 2504 px, 120 Hz Display with ...",200 MP + 50 MP + 10 MP Triple Rear & 10 MP Fro...,200 MP + 50 MP + 10 MP Triple Rear & 10 MP Fro...,Android v17
384,384,Apple iPhone Duo,299900,81,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20 Pro, Hexa Core Processor","12 GB RAM, 256 GB inbuilt",5800 mAh Battery with Fast Charging,"7.6 inches, 1878 x 2670 px, 120 Hz Display",48 MP + 48 MP Dual Rear & Under-display FaceTi...,48 MP + 48 MP Dual Rear & Under-display FaceTi...,Memory Card Not Supported
389,389,Samsung Galaxy Z Flip 3,41499,67,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3300 mAh Battery with 15W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",12 MP + 12 MP Dual Rear & 10 MP Front Camera,12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
391,391,Samsung Galaxy Z Fold 8 5G,174999,92,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 for Galaxy, Octa Core...","12 GB RAM, 256 GB inbuilt",4800 mAh Battery with 45W Fast Charging,"7.6 inches, 1828 x 2448 px, 120 Hz Display wit...",50 MP + 50 MP Dual Rear & 10 MP Front Camera,50 MP + 50 MP Dual Rear & 10 MP Front Camera,Android v17
421,421,Samsung Galaxy Z Fold 7,174999,94,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite for Galaxy, Octa Core, 4.47...","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"8 inches, 1968 x 2184 px, 120 Hz Display with ...",200 MP + 12 MP + 10 MP Triple Rear & 10 MP Fro...,200 MP + 12 MP + 10 MP Triple Rear & 10 MP Fro...,Android v16
580,580,Google Pixel 11 Pro Fold,186999,86,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi",Tensor G6,"16 GB RAM, 512 GB inbuilt",4806 mAh Battery with Fast Charging,"8 inches, 2076 x 2152 px, 120 Hz Display with ...",48 MP + 10.8 MP + 10.5 MP Triple Rear & 10 MP ...,48 MP + 10.8 MP + 10.5 MP Triple Rear & 10 MP ...,Android v17
583,583,Samsung Galaxy Z Fold 8 Ultra (16GB RAM + 1TB),254999,98,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 For Galaxy, Octa Core...","16 GB RAM, 1 TB inbuilt",5000 mAh Battery with 45W Fast Charging,"8 inches, 2256 x 2504 px, 120 Hz Display with ...",200 MP + 50 MP + 10 MP Triple Rear & 10 MP Fro...,200 MP + 50 MP + 10 MP Triple Rear & 10 MP Fro...,Android v17
605,605,Samsung Galaxy Z Flip 6 5G,69895,84,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen3, Octa Core, 3.3 GHz Processor","12 GB RAM, 256 GB inbuilt",4000 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",50 MP + 12 MP Dual Rear & 10 MP Front Camera,50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
616,616,Samsung Galaxy Z Fold 4,89149,84,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
632,632,Motorola Razr Fold (16GB RAM + 512GB),159999,97,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen5, Octa Core, 3.8 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"8.09 inches, 2232 x 2484 px, 120 Hz Display wi...",50 MP + 50 MP + 50 MP Triple Rear & 32 MP Fron...,50 MP + 50 MP + 50 MP Triple Rear & 32 MP Fron...,Memory Card Not Supported
665,665,Samsung Galaxy Z Flip 4 (8GB RAM + 256GB),51999,72,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",3700 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",12 MP + 12 MP Dual Rear & 10 MP Front Camera,12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
671,671,Apple iPhone Duo (1TB),374900,83,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20 Pro, Hexa Core Processor","12 GB RAM, 1 TB inbuilt",5800 mAh Battery with Fast Charging,"7.6 inches, 1878 x 2670 px, 120 Hz Display",48 MP + 48 MP Dual Rear & Under-display FaceTi...,48 MP + 48 MP Dual Rear & Under-display FaceTi...,Memory Card Not Supported
681,681,Samsung Galaxy Z Fold 8 Ultra (12GB RAM + 512GB),214999,98,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 For Galaxy, Octa Core...","12 GB RAM, 512 GB inbuilt",5000 mAh Battery with 45W Fast Charging,"8 inches, 2256 x 2504 px, 120 Hz Display with ...",200 MP + 50 MP + 10 MP Triple Rear & 10 MP Fro...,200 MP + 50 MP + 10 MP Triple Rear & 10 MP Fro...,Android v17
685,685,Motorola Razr Fold,149999,95,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen5, Octa Core, 3.8 GHz Processor","12 GB RAM, 256 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"8.09 inches, 2232 x 2484 px, 120 Hz Display wi...",50 MP + 50 MP + 50 MP Triple Rear & 32 MP Fron...,50 MP + 50 MP + 50 MP Triple Rear & 32 MP Fron...,Memory Card Not Supported
686,686,Ai+ Nova Flip,49999,74,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Dimensity 7300X, Octa Core, 2.5 GHz Processor","8 GB RAM, 256 GB inbuilt",4325 mAh Battery with Fast Charging,"6.9 inches, 2790 x 1188 px Display with Punch ...",50 MP + 2 MP Dual Rear & 32 MP Front Camera,50 MP + 2 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
696,696,Samsung Galaxy Z Flip 7 5G,92900,88,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Exynos 2500, Deca Core, 3.3 GHz Processor","12 GB RAM, 256 GB inbuilt",4300 mAh Battery with 25W Fast Charging,"6.9 inches, 1080 x 2520 px, 120 Hz Display wit...",50 MP + 12 MP Dual Rear & 10 MP Front Camera,50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
704,704,Samsung Galaxy Z Fold 6,134999,86,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen 3, Octa Core, 3.39 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1856 x 2160 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 4 MP Front...,50 MP + 12 MP + 10 MP Triple Rear & 4 MP Front...,Android v14
706,706,Vivo X Fold 3 Pro,124499,93,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Gen3, Octa Core, 3.3 GHz Processor","16 GB RAM, 512 GB inbuilt",5700 mAh Battery with 100W Fast Charging,"8.03 inches, 2200 x 2480 px, 120 Hz Display wi...",64 MP + 50 MP + 50 MP Triple Rear & 32 MP Fron...,64 MP + 50 MP + 50 MP Triple Rear & 32 MP Fron...,Memory Card Not Supported
713,713,Samsung Galaxy Z Fold 5 (12GB RAM + 512GB),122999,83,"Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi","Snapdragon 8 Gen 2, Octa Core, 3.36 GHz Processor","12 GB RAM, 512 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 4 MP Front...,50 MP + 12 MP + 10 MP Triple Rear & 4 MP Front...,Android v13
734,734,Apple iPhone Duo (512GB),324900,83,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20 Pro, Hexa Core Processor","12 GB RAM, 512 GB inbuilt",5800 mAh Battery with Fast Charging,"7.6 inches, 1878 x 2670 px, 120 Hz Display",48 MP + 48 MP Dual Rear & Under-display FaceTi...,48 MP + 48 MP Dual Rear & Under-display FaceTi...,Memory Card Not Supported
743,743,Samsung Galaxy Z Fold 8 (16GB RAM + 1TB),234999,93,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 for Galaxy, Octa Core...","16 GB RAM, 1 TB inbuilt",4800 mAh Battery with 45W Fast Charging,"7.6 inches, 1828 x 2448 px, 120 Hz Display wit...",50 MP + 50 MP Dual Rear & 10 MP Front Camera,50 MP + 50 MP Dual Rear & 10 MP Front Camera,Android v17
744,744,Samsung Galaxy Z Flip 8 5G,114999,92,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Exynos 2600, Deca Core, 3.8 GHz Processor","12 GB RAM, 256 GB inbuilt",4300 mAh Battery with 25W Fast Charging,"6.9 inches, 1080 x 2520 px, 120 Hz Display wit...",50 MP + 12 MP Dual Rear & 10 MP Front Camera,50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
769,769,Google Pixel 10 Pro Fold,162998,88,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Tensor G5, Octa Core, 3.78 GHz Processor","16 GB RAM, 256 GB inbuilt",5015 mAh Battery with 30W Fast Charging,"8 inches, 2076 x 2152 px, 120 Hz Display with ...",48 MP + 10.8 MP + 10.5 MP Triple Rear & 10 MP ...,48 MP + 10.8 MP + 10.5 MP Triple Rear & 10 MP ...,Android v16
776,776,Vivo X Fold 5 5G,149999,89,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Gen3, Octa Core, 3.3 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"8.03 inches, 2200 x 2480 px, 120 Hz Display wi...",50 MP + 50 MP + 50 MP Triple Rear & 20 MP Fron...,50 MP + 50 MP + 50 MP Triple Rear & 20 MP Fron...,Android v15
789,789,Google Pixel 9 Pro Fold,135900,83,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Tensor G4, Octa Core, 3.1 GHz Processor","16 GB RAM, 256 GB inbuilt",4650 mAh Battery with Fast Charging,"8.03 inches, 2152 x 2076 px, 120 Hz Display wi...",48 MP + 10.8 MP + 10.5 MP Triple Rear & 10 MP ...,48 MP + 10.8 MP + 10.5 MP Triple Rear & 10 MP ...,Android v14
808,808,Samsung Galaxy Z Flip 5,62699,76,"Single Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi","Snapdragon 8 Gen 2, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",3700 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",12 MP + 12 MP Dual Rear & 10 MP Front Camera,12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
809,809,Samsung Galaxy Z Fold 5,119999,84,"Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi","Snapdragon 8 Gen 2, Octa Core, 3.36 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 4 MP Front...,50 MP + 12 MP + 10 MP Triple Rear & 4 MP Front...,Android v13
811,811,Motorola Razr 40,54990,77,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Snapdragon 7 Gen1, Octa Core, 2.4 GHz Processor","8 GB RAM, 256 GB inbuilt",4200 mAh Battery with 30W Fast Charging,"6.9 inches, 1080 x 2640 px, 144 Hz Display wit...",64 MP + 13 MP Dual Rear & 32 MP Front Camera,64 MP + 13 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
820,820,Microsoft Surface Duo 2,89990,71,"Single Sim, 5G, VoLTE, NFC, Wi-Fi","Snapdragon 888 , Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",4449 mAh Battery with 23W Fast Charging,"8.3 inches, 1892 x 2688 px, 90 Hz Display",16 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,16 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Android v11
857,857,Samsung Galaxy Z Fold 8 (12GB RAM + 512GB),194999,92,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 for Galaxy, Octa Core...","12 GB RAM, 512 GB inbuilt",4800 mAh Battery with 45W Fast Charging,"7.6 inches, 1828 x 2448 px, 120 Hz Display wit...",50 MP + 50 MP Dual Rear & 10 MP Front Camera,50 MP + 50 MP Dual Rear & 10 MP Front Camera,Android v17
880,880,Samsung Galaxy Z Flip 7 FE 5G,89999,83,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Exynos 2400, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",4000 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",50 MP + 12 MP Dual Rear & 10 MP Front Camera,50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
881,881,Samsung Galaxy Z Fold 7 (12GB RAM + 512GB),186999,95,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite for Galaxy, Octa Core, 4.47...","12 GB RAM, 512 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"8 inches, 1968 x 2184 px, 120 Hz Display with ...",200 MP + 12 MP + 10 MP Triple Rear & 10 MP Fro...,200 MP + 12 MP + 10 MP Triple Rear & 10 MP Fro...,Android v16
917,917,Motorola Razr 40 Ultra,59990,74,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",3800 mAh Battery with 30W Fast Charging,"6.9 inches, 1080 x 2640 px, 165 Hz Display wit...",13 MP + 12 MP Dual Rear & 32 MP Front Camera,13 MP + 12 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
934,934,Samsung Galaxy Z Fold 4 (12GB RAM + 512GB),90999,83,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 512 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
985,985,Samsung Galaxy Z Flip 8 5G (12GB RAM + 512GB),134999,92,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Exynos 2600, Deca Core, 3.8 GHz Processor","12 GB RAM, 512 GB inbuilt",4300 mAh Battery with 25W Fast Charging,"6.9 inches, 1080 x 2520 px, 120 Hz Display wit...",50 MP + 12 MP Dual Rear & 10 MP Front Camera,50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
1015,1015,Samsung Galaxy Z Flip 7 FE (8GB RAM + 256GB),95999,84,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Exynos 2400, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",4000 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",50 MP + 12 MP Dual Rear & 10 MP Front Camera,50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
1016,1016,Samsung Galaxy Z Flip 7 5G (12GB RAM+512GB),121999,89,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Exynos 2500, Deca Core, 3.3 GHz Processor","12 GB RAM, 512 GB inbuilt",4300 mAh Battery with 25W Fast Charging,"6.9 inches, 1080 x 2520 px, 120 Hz Display wit...",50 MP + 12 MP Dual Rear & 10 MP Front Camera,50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported

In [442]:
df1['Memory Card'].value_counts()

Memory Card
Memory Card Not Supported                                                                         213
Memory Card (Hybrid), upto 1 TB                                                                   104
Memory Card (Hybrid), upto 2 TB                                                                    84
Android v16                                                                                        80
Memory Card (Hybrid)                                                                               71
Android v15                                                                                        70
Memory Card Supported, upto 1 TB                                                                   64
Memory Card Supported                                                                              39
Memory Card Supported, upto 2 TB                                                                   30
Android v14                                                                                        27
Android v12                                                                                        27
Android v13                                                                                        14
Memory Card Supported, upto 512 GB                                                                 12
Memory Card Supported, upto 256 GB                                                                 11
Memory Card (Hybrid), upto 1.5 TB                                                                   9
Memory Card (Hybrid), upto 128 GB                                                                   7
50 MP + 12 MP Dual Rear & 10 MP Front Camera                                                        7
Android v17                                                                                         6
48 MP + 48 MP Dual Rear & Under-display FaceTime\n                      Camera Front Camera         4
Memory Card Supported, upto 128 GB                                                                  3
50 MP + 50 MP Dual Rear & 10 MP Front Camera                                                        3
200 MP + 50 MP + 10 MP Triple Rear & 10 MP Front\n                      Camera                      3
Android v11                                                                                         3
12 MP + 12 MP Dual Rear & 10 MP Front Camera                                                        3
50 MP + 12 MP + 10 MP Triple Rear & 4 MP Front Camera                                               3
50 MP + 50 MP + 50 MP Triple Rear & 32 MP Front Camera                                              2
Memory Card (Hybrid), upto 512 GB                                                                   2
200 MP + 12 MP + 10 MP Triple Rear & 10 MP Front\n                      Camera                      2
50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 MP Dual\n                      Front Camera           2
48 MP + 10.8 MP + 10.5 MP Triple Rear & 10 MP Front\n                      Camera                   2
200 MP + 50 MP + 50 MP Triple Rear & 20 MP Front\n                      Camera                      1
50 MP Dual Rear & 13 MP Front Camera                                                                1
Android v12.0                                                                                       1
Memory Card (Hybrid), upto 256 GB                                                                   1
50 MP + 2 MP Dual Rear & 32 MP Front Camera                                                         1
50 MP + 50 MP + 50 MP Triple Rear & 20 MP Front Camera                                              1
48 MP + 10.8 MP + 10.5 MP Triple Rear & 10 MP + 10 MP\n                      Dual Front Camera      1
64 MP + 50 MP + 50 MP Triple Rear & 32 MP Front Camera                                              1
16 MP + 12 MP + 12 MP Triple Rear & 12 MP Front Camera                                              1
64 MP + 13 MP Dual Rear & 32 MP Front Camera                                                        1
Memory Card Supported, upto 64 GB                                                                   1
Android v13.0                                                                                       1
13 MP + 12 MP Dual Rear & 32 MP Front Camera                                                        1
Android v10                                                                                         1
Android                                                                                             1
Android v8.1 (Oreo)                                                                                 1
Name: count, dtype: int64

In [443]:
temp_df = df1[df1['Memory Card'].str.contains('MP')]

In [444]:
df1.loc[temp_df.index,'Memory Card'] = 'Memory Card Not Supported'

In [445]:
temp_df = df1[df1['Memory Card'].str.contains('Android')]

In [446]:
df1.loc[temp_df.index,'OS'] = temp_df['Memory Card'].values

In [447]:
df1.loc[temp_df.index,'Memory Card'] = 'Memory Card Not Supported'

In [459]:
df1['OS'].value_counts()

OS
Android v16                   233
Android v15                   161
Android v14                    83
Android v13                    48
Android v12                    31
Android v11                    31
Memory Card Not Supported      20
Android v17                    14
Android v10                    11
iOS v26                        11
iOS v27                         8
Android v9.0 (Pie)              7
iOS v18                         6
Android v8.1 (Oreo)             4
iOS v17                         3
Android v10.0                   3
iOS v26.3                       2
Android 15 Go                   2
iOS v11                         2
Android 15 Go Edition           2
Android v6.0 (Marshmallow)      1
Android v14.0                   1
v60                             1
Name: count, dtype: int64

In [460]:
temp_df = df1[df1['OS'] == 'Memory Card Not Supported']

In [461]:
df1.loc[temp_df.index,'OS'] = np.nan

In [450]:
temp_df = df1[df1['OS'] == 'Bluetooth']

In [451]:
df1.loc[temp_df.index,'OS'] = np.nan

In [452]:
temp_df = df1[df1['OS'] == 'No FM Radio']

In [453]:
df1.loc[temp_df.index,'OS'] = np.nan

In [462]:
df1.shape

(923, 12)

In [463]:
df1

,index,Name,Price,Spec Score,SIM,Processor,RAM,Battery,Display,Camera,Memory Card,OS
0,0,Vivo V80 5G,62999,84,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 7 Gen4, Octa Core, 2.8 GHz Processor","8 GB RAM, 128 GB inbuilt",7200 mAh Battery with 90W Fast Charging,"6.59 inches, 1260 x 2750 px, 144 Hz Display wi...",50 MP + 50 MP + 8 MP Triple Rear & 50 MP Front...,Memory Card Not Supported,Android v17
1,1,Samsung Galaxy S25 Ultra,99999,92,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite for Galaxy, Octa Core, 4.47...","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 45W Fast Charging,"6.9 inches, 1440 x 3120 px, 120 Hz Display wit...",200 MP Quad Rear & 12 MP Front Camera,Memory Card Not Supported,Android v15
2,2,Samsung Galaxy S23 5G,49999,74,"Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi","Snapdragon 8 Gen 2, Octa Core, 3.36 GHz Processor","8 GB RAM, 128 GB inbuilt",3900 mAh Battery with 25W Fast Charging,"6.1 inches, 1080 x 2340 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,NaN
3,3,Motorola Edge 70 Fusion,29299,70,"Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi","Snapdragon 7s Gen4, Octa Core, 2.7 GHz Processor","8 GB RAM, 128 GB inbuilt",7000 mAh Battery with 68W Fast Charging,"6.8 inches, 1272 x 2772 px, 144 Hz Display wit...",50 MP + 13 MP + Dedicated 3-in-1 light sensor ...,Memory Card Not Supported,NaN
4,4,OPPO K14 Plus 5G,29999,67,"Dual Sim, 5G, VoLTE, Wi-Fi, IR Blaster","Dimensity 7360 Max, Octa Core, 2.5 GHz Processor","6 GB RAM, 128 GB inbuilt",8000 mAh Battery with 45W Fast Charging,"6.78 inches, 1272 x 2772 px, 144 Hz Display wi...",50 MP + 2 MP Dual Rear & 16 MP Front Camera,Memory Card Not Supported,Android v16
...,...,...,...,...,...,...,...,...,...,...,...,...
918,1006,Peace Nova 16 Pro 4G,9999,34,"Dual Sim, 4G, VoLTE, Wi-Fi","Helio, Single Core, 1.7 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery,"6.56 inches, 1640 x 720 px Display",20 MP Rear & 8 MP Front Camera,"Memory Card (Hybrid), upto 128 GB",NaN
919,1007,Peace Nova 11 4G,7999,26,"Dual Sim, 4G, Wi-Fi",Helio 6739,"4 GB RAM, 64 GB inbuilt",2000 mAh Battery,6.56 inches Display,20 MP Rear & 5 MP Front Camera,"Memory Card Supported, upto 128 GB",NaN
920,1010,iKall Z10 4G 2025,8499,37,"Dual Sim, 4G, VoLTE, Wi-Fi","Octa Core, 2 GHz Processor","4 GB RAM, 64 GB inbuilt",4000 mAh Battery,"6.53 inches, 720 x 1600 px Display",20 MP Rear & 8 MP Front Camera,Memory Card (Hybrid),Android v14
921,1015,Samsung Galaxy Z Flip 7 FE (8GB RAM + 256GB),95999,84,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Exynos 2400, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",4000 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported,NaN
922,1016,Samsung Galaxy Z Flip 7 5G (12GB RAM+512GB),121999,89,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Exynos 2500, Deca Core, 3.3 GHz Processor","12 GB RAM, 512 GB inbuilt",4300 mAh Battery with 25W Fast Charging,"6.9 inches, 1080 x 2520 px, 120 Hz Display wit...",50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported,NaN

In [464]:
df1 = df1.reset_index(drop=True)

In [465]:
df1

,index,Name,Price,Spec Score,SIM,Processor,RAM,Battery,Display,Camera,Memory Card,OS
0,0,Vivo V80 5G,62999,84,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 7 Gen4, Octa Core, 2.8 GHz Processor","8 GB RAM, 128 GB inbuilt",7200 mAh Battery with 90W Fast Charging,"6.59 inches, 1260 x 2750 px, 144 Hz Display wi...",50 MP + 50 MP + 8 MP Triple Rear & 50 MP Front...,Memory Card Not Supported,Android v17
1,1,Samsung Galaxy S25 Ultra,99999,92,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite for Galaxy, Octa Core, 4.47...","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 45W Fast Charging,"6.9 inches, 1440 x 3120 px, 120 Hz Display wit...",200 MP Quad Rear & 12 MP Front Camera,Memory Card Not Supported,Android v15
2,2,Samsung Galaxy S23 5G,49999,74,"Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi","Snapdragon 8 Gen 2, Octa Core, 3.36 GHz Processor","8 GB RAM, 128 GB inbuilt",3900 mAh Battery with 25W Fast Charging,"6.1 inches, 1080 x 2340 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,NaN
3,3,Motorola Edge 70 Fusion,29299,70,"Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi","Snapdragon 7s Gen4, Octa Core, 2.7 GHz Processor","8 GB RAM, 128 GB inbuilt",7000 mAh Battery with 68W Fast Charging,"6.8 inches, 1272 x 2772 px, 144 Hz Display wit...",50 MP + 13 MP + Dedicated 3-in-1 light sensor ...,Memory Card Not Supported,NaN
4,4,OPPO K14 Plus 5G,29999,67,"Dual Sim, 5G, VoLTE, Wi-Fi, IR Blaster","Dimensity 7360 Max, Octa Core, 2.5 GHz Processor","6 GB RAM, 128 GB inbuilt",8000 mAh Battery with 45W Fast Charging,"6.78 inches, 1272 x 2772 px, 144 Hz Display wi...",50 MP + 2 MP Dual Rear & 16 MP Front Camera,Memory Card Not Supported,Android v16
...,...,...,...,...,...,...,...,...,...,...,...,...
918,1006,Peace Nova 16 Pro 4G,9999,34,"Dual Sim, 4G, VoLTE, Wi-Fi","Helio, Single Core, 1.7 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery,"6.56 inches, 1640 x 720 px Display",20 MP Rear & 8 MP Front Camera,"Memory Card (Hybrid), upto 128 GB",NaN
919,1007,Peace Nova 11 4G,7999,26,"Dual Sim, 4G, Wi-Fi",Helio 6739,"4 GB RAM, 64 GB inbuilt",2000 mAh Battery,6.56 inches Display,20 MP Rear & 5 MP Front Camera,"Memory Card Supported, upto 128 GB",NaN
920,1010,iKall Z10 4G 2025,8499,37,"Dual Sim, 4G, VoLTE, Wi-Fi","Octa Core, 2 GHz Processor","4 GB RAM, 64 GB inbuilt",4000 mAh Battery,"6.53 inches, 720 x 1600 px Display",20 MP Rear & 8 MP Front Camera,Memory Card (Hybrid),Android v14
921,1015,Samsung Galaxy Z Flip 7 FE (8GB RAM + 256GB),95999,84,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Exynos 2400, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",4000 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported,NaN
922,1016,Samsung Galaxy Z Flip 7 5G (12GB RAM+512GB),121999,89,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Exynos 2500, Deca Core, 3.3 GHz Processor","12 GB RAM, 512 GB inbuilt",4300 mAh Battery with 25W Fast Charging,"6.9 inches, 1080 x 2520 px, 120 Hz Display wit...",50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported,NaN

In [466]:
df1.to_csv('smartphones_cleaned_secondphase.csv',index=False)

In [467]:
brand_name = df1['Name'].str.split(' ').str.get(0)

In [468]:
df1.insert(1,'Brand Name',brand_name)

In [470]:
df1['Brand Name'] = df1['Brand Name'].str.lower()

In [471]:
df1

,index,Brand Name,Name,Price,Spec Score,SIM,Processor,RAM,Battery,Display,Camera,Memory Card,OS
0,0,vivo,Vivo V80 5G,62999,84,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 7 Gen4, Octa Core, 2.8 GHz Processor","8 GB RAM, 128 GB inbuilt",7200 mAh Battery with 90W Fast Charging,"6.59 inches, 1260 x 2750 px, 144 Hz Display wi...",50 MP + 50 MP + 8 MP Triple Rear & 50 MP Front...,Memory Card Not Supported,Android v17
1,1,samsung,Samsung Galaxy S25 Ultra,99999,92,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite for Galaxy, Octa Core, 4.47...","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 45W Fast Charging,"6.9 inches, 1440 x 3120 px, 120 Hz Display wit...",200 MP Quad Rear & 12 MP Front Camera,Memory Card Not Supported,Android v15
2,2,samsung,Samsung Galaxy S23 5G,49999,74,"Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi","Snapdragon 8 Gen 2, Octa Core, 3.36 GHz Processor","8 GB RAM, 128 GB inbuilt",3900 mAh Battery with 25W Fast Charging,"6.1 inches, 1080 x 2340 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,NaN
3,3,motorola,Motorola Edge 70 Fusion,29299,70,"Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi","Snapdragon 7s Gen4, Octa Core, 2.7 GHz Processor","8 GB RAM, 128 GB inbuilt",7000 mAh Battery with 68W Fast Charging,"6.8 inches, 1272 x 2772 px, 144 Hz Display wit...",50 MP + 13 MP + Dedicated 3-in-1 light sensor ...,Memory Card Not Supported,NaN
4,4,oppo,OPPO K14 Plus 5G,29999,67,"Dual Sim, 5G, VoLTE, Wi-Fi, IR Blaster","Dimensity 7360 Max, Octa Core, 2.5 GHz Processor","6 GB RAM, 128 GB inbuilt",8000 mAh Battery with 45W Fast Charging,"6.78 inches, 1272 x 2772 px, 144 Hz Display wi...",50 MP + 2 MP Dual Rear & 16 MP Front Camera,Memory Card Not Supported,Android v16
...,...,...,...,...,...,...,...,...,...,...,...,...,...
918,1006,peace,Peace Nova 16 Pro 4G,9999,34,"Dual Sim, 4G, VoLTE, Wi-Fi","Helio, Single Core, 1.7 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery,"6.56 inches, 1640 x 720 px Display",20 MP Rear & 8 MP Front Camera,"Memory Card (Hybrid), upto 128 GB",NaN
919,1007,peace,Peace Nova 11 4G,7999,26,"Dual Sim, 4G, Wi-Fi",Helio 6739,"4 GB RAM, 64 GB inbuilt",2000 mAh Battery,6.56 inches Display,20 MP Rear & 5 MP Front Camera,"Memory Card Supported, upto 128 GB",NaN
920,1010,ikall,iKall Z10 4G 2025,8499,37,"Dual Sim, 4G, VoLTE, Wi-Fi","Octa Core, 2 GHz Processor","4 GB RAM, 64 GB inbuilt",4000 mAh Battery,"6.53 inches, 720 x 1600 px Display",20 MP Rear & 8 MP Front Camera,Memory Card (Hybrid),Android v14
921,1015,samsung,Samsung Galaxy Z Flip 7 FE (8GB RAM + 256GB),95999,84,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Exynos 2400, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",4000 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported,NaN
922,1016,samsung,Samsung Galaxy Z Flip 7 5G (12GB RAM+512GB),121999,89,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Exynos 2500, Deca Core, 3.3 GHz Processor","12 GB RAM, 512 GB inbuilt",4300 mAh Battery with 25W Fast Charging,"6.9 inches, 1080 x 2520 px, 120 Hz Display wit...",50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported,NaN

In [472]:
has_5g = df1['SIM'].str.contains('5G')
has_nfc = df1['SIM'].str.contains('NFC')
has_ir_blaster = df1['SIM'].str.contains('IR Blaster')

In [473]:
df1.insert(6,'Has 5G',has_5g)
df1.insert(7,'Has NFC',has_nfc)
df1.insert(8,'Has IR Blaster',has_ir_blaster)

In [474]:
df1.head()

,index,Brand Name,Name,Price,Spec Score,SIM,Has 5G,Has NFC,Has IR Blaster,Processor,RAM,Battery,Display,Camera,Memory Card,OS
0,0,vivo,Vivo V80 5G,62999,84,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster",True,True,True,"Snapdragon 7 Gen4, Octa Core, 2.8 GHz Processor","8 GB RAM, 128 GB inbuilt",7200 mAh Battery with 90W Fast Charging,"6.59 inches, 1260 x 2750 px, 144 Hz Display wi...",50 MP + 50 MP + 8 MP Triple Rear & 50 MP Front...,Memory Card Not Supported,Android v17
1,1,samsung,Samsung Galaxy S25 Ultra,99999,92,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi",True,True,False,"Snapdragon 8 Elite for Galaxy, Octa Core, 4.47...","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 45W Fast Charging,"6.9 inches, 1440 x 3120 px, 120 Hz Display wit...",200 MP Quad Rear & 12 MP Front Camera,Memory Card Not Supported,Android v15
2,2,samsung,Samsung Galaxy S23 5G,49999,74,"Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi",True,True,False,"Snapdragon 8 Gen 2, Octa Core, 3.36 GHz Processor","8 GB RAM, 128 GB inbuilt",3900 mAh Battery with 25W Fast Charging,"6.1 inches, 1080 x 2340 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,NaN
3,3,motorola,Motorola Edge 70 Fusion,29299,70,"Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi",True,True,False,"Snapdragon 7s Gen4, Octa Core, 2.7 GHz Processor","8 GB RAM, 128 GB inbuilt",7000 mAh Battery with 68W Fast Charging,"6.8 inches, 1272 x 2772 px, 144 Hz Display wit...",50 MP + 13 MP + Dedicated 3-in-1 light sensor ...,Memory Card Not Supported,NaN
4,4,oppo,OPPO K14 Plus 5G,29999,67,"Dual Sim, 5G, VoLTE, Wi-Fi, IR Blaster",True,False,True,"Dimensity 7360 Max, Octa Core, 2.5 GHz Processor","6 GB RAM, 128 GB inbuilt",8000 mAh Battery with 45W Fast Charging,"6.78 inches, 1272 x 2772 px, 144 Hz Display wi...",50 MP + 2 MP Dual Rear & 16 MP Front Camera,Memory Card Not Supported,Android v16

In [475]:
processor_name = df1['Processor'].str.split(',').str.get(0)
num_cores = df1['Processor'].str.split(',').str.get(1)
processor_speed = df1['Processor'].str.split(',').str.get(2)

In [476]:
df1.insert(10,'Processor Name',processor_name)
df1.insert(11,'Number of Cores',num_cores)
df1.insert(12,'Processor Speed',processor_speed)

In [484]:
df1.loc[1,'Processor Speed'] = '4.47 GHz Processor'

In [550]:
df1.head()

,index,Brand Name,Name,Price,Spec Score,SIM,Has 5G,Has NFC,Has IR Blaster,Processor,Processor Name,Number of Cores,Processor Speed,RAM,Battery,Display,Camera,Memory Card,OS
0,0,vivo,Vivo V80 5G,62999,84,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster",True,True,True,"Snapdragon 7 Gen4, Octa Core, 2.8 GHz Processor",Snapdragon 7 Gen4,Octa Core,2.8 GHz Processor,"8 GB RAM, 128 GB inbuilt",7200 mAh Battery with 90W Fast Charging,"6.59 inches, 1260 x 2750 px, 144 Hz Display wi...",50 MP + 50 MP + 8 MP Triple Rear & 50 MP Front...,Memory Card Not Supported,Android v17
1,1,samsung,Samsung Galaxy S25 Ultra,99999,92,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi",True,True,False,"Snapdragon 8 Elite for Galaxy, Octa Core, 4.47...",Snapdragon 8 Elite for Galaxy,Octa Core,4.47 GHz Processor,"12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 45W Fast Charging,"6.9 inches, 1440 x 3120 px, 120 Hz Display wit...",200 MP Quad Rear & 12 MP Front Camera,Memory Card Not Supported,Android v15
2,2,samsung,Samsung Galaxy S23 5G,49999,74,"Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi",True,True,False,"Snapdragon 8 Gen 2, Octa Core, 3.36 GHz Processor",Snapdragon 8 Gen 2,Octa Core,3.36 GHz Processor,"8 GB RAM, 128 GB inbuilt",3900 mAh Battery with 25W Fast Charging,"6.1 inches, 1080 x 2340 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,NaN
3,3,motorola,Motorola Edge 70 Fusion,29299,70,"Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi",True,True,False,"Snapdragon 7s Gen4, Octa Core, 2.7 GHz Processor",Snapdragon 7s Gen4,Octa Core,2.7 GHz Processor,"8 GB RAM, 128 GB inbuilt",7000 mAh Battery with 68W Fast Charging,"6.8 inches, 1272 x 2772 px, 144 Hz Display wit...",50 MP + 13 MP + Dedicated 3-in-1 light sensor ...,Memory Card Not Supported,NaN
4,4,oppo,OPPO K14 Plus 5G,29999,67,"Dual Sim, 5G, VoLTE, Wi-Fi, IR Blaster",True,False,True,"Dimensity 7360 Max, Octa Core, 2.5 GHz Processor",Dimensity 7360 Max,Octa Core,2.5 GHz Processor,"6 GB RAM, 128 GB inbuilt",8000 mAh Battery with 45W Fast Charging,"6.78 inches, 1272 x 2772 px, 144 Hz Display wi...",50 MP + 2 MP Dual Rear & 16 MP Front Camera,Memory Card Not Supported,Android v16

In [487]:
pd.set_option('display.max_rows', None)

In [561]:
df1[df1['Processor Name'].str.contains('Core')]

Empty DataFrame
Columns: [index, Brand Name, Name, Price, Spec Score, SIM, Has 5G, Has NFC, Has IR Blaster, Processor, Processor Name, Number of Cores, Processor Speed, RAM, Battery, Display, Camera, Memory Card, OS]
Index: []

In [570]:
df1['Processor Name'].value_counts()

Processor Name
Dimensity 6300                            118
Unisoc T7250                               24
Snapdragon 6 Gen3                          20
Snapdragon 7 Gen4                          18
Snapdragon 7s Gen4                         17
Exynos 1380                                15
Dimensity 7400 Ultra                       14
Snapdragon 8 Gen5                          14
Snapdragon 4 Gen2                          14
Snapdragon 8s Gen3                         13
Dimensity 7100                             13
Dimensity 6400                             12
Unisoc T8200                               12
Apple A20 Pro                              12
Snapdragon 695                             11
Dimensity 7300 Energy                      11
Exynos 1330                                11
Dimensity 7400                             10
Apple A19 Pro                              10
Snapdragon 8 Elite                         10
Exynos 2400                                 9
Snapdragon 8s Gen4                          9
Dimensity 7050                              9
Snapdragon 8 Elite Gen 5                    9
Snapdragon 8 Gen1                           9
Dimensity 7500 Turbo                        8
Snapdragon 8 Gen3                           8
Snapdragon 6 Gen4                           8
Snapdragon 6s Gen4                          7
Dimensity 8350                              7
Helio G85                                   7
Dimensity 8450                              7
Dimensity 6360 MAX                          7
Dimensity 7400 Turbo                        7
Dimensity 7360 Turbo                        7
Tensor G6                                   7
Unisoc T8300                                7
Exynos 1480                                 7
Exynos 1280                                 7
Snapdragon 7 Gen3                           6
Snapdragon 7s Gen2                          6
Dimensity 1080                              6
Snapdragon 8+ Gen1                          6
Helio                                       6
Dimensity 6100 Plus                         6
Snapdragon 8 Gen 2                          6
Dimensity 7360 Max                          6
Dimensity 8500 Ultra                        6
Snapdragon 888                              6
Snapdragon 8 Elite Gen 5 for Galaxy         6
Bionic A18                                  5
Snapdragon 8 Elite for Galaxy               5
Helio G81                                   5
Helio G99                                   5
Dimensity 7300                              5
Snapdragon 7s Gen 2                         5
Snapdragon 7 Gen 4                          5
Exynos 2600                                 5
Snapdragon 7s Gen3                          5
Tensor G4                                   5
Snapdragon 7 Gen1                           5
Unisoc T7100                                5
Exynos 2500                                 4
Dimensity 6360 Apex                         4
Dimensity 7300 Ultra                        4
Snapdragon 4 Gen5                           4
Snapdragon 4 Gen4                           4
Snapdragon 6 Gen1                           4
Tensor G5                                   4
Snapdragon 6 Gen5                           4
Dimensity 9400                              4
Dimensity 6020                              4
Snapdragon 778G                             4
Unisoc T765                                 4
MediaTek MT6739                             4
Dimensity 6080                              4
Snapdragon 680                              4
Snapdragon 6s Gen3                          4
Dimensity 7300 Max                          4
Dimensity 9500s                             4
Dimensity 920 5G                            4
Dimensity 810 5G                            4
Dimensity 9400e                             3
Bionic A16                                  3
Dimensity 8350 Extreme                      3
Dimensity 6400 Turbo                        3
Dimensity 7400 Apex                         3
Tensor G3                                   3
Snapdragon 8 Gen2                           3
Snapdragon 865                              3
Dimensity 7020                              3
Tensor G2                                   3
Not Available                               3
Exynos 1580                                 3
Dimensity 8350 Ultra                        3
Dimensity 8400-MAX                          3
Dimensity 8500 Extreme                      3
Apple A19                                   3
Dimensity 9500                              3
Dimensity 7400 Ultimate                     3
Helio G96                                   3
Snapdragon 888                              3
Snapdragon 732G                             3
Dimensity 700 5G                            3
Snapdragon 8 Elite Gen 5 For Galaxy         3
Snapdragon 855+                             2
Unisoc T760                                 2
Exynos 2400e                                2
Dimensity 7300e                             2
Unisoc SC9863A                              2
Apple A11                                   2
Snapdragon 665                              2
Dimensity 7025 Ultra                        2
Dimensity 7300 Pro                          2
Exynos 1680                                 2
Unisoc T606                                 2
Dimensity 7300 Plus                         2
Dimensity 6400 Max                          2
Snapdragon 855                              2
MediaTek MTK6762                            2
Snapdragon 750G                             2
Unisoc T603                                 2
Helio G88                                   2
Dimensity 1300                              2
Dimensity 7200 Ultra                        2
Exynos 2200                                 2
Dimensity 7030                              2
Helio G81 Ultimate                          2
Unisoc T7225                                2
Unisoc T612                                 2
Tensor                                      2
Snapdragon 7 Gen 1 Accelerated Edition      2
Snapdragon 662                              2
Snapdragon 720G                             2
MTK6739                                     2
Snapdragon 695                              2
Helio G80                                   2
Dimensity 9500 Super Edition                1
Dimensity 7300 Ultimate                     1
Snapdragon 7+ Gen3                          1
Dimensity 8350 Apex                         1
Snapdragon 4s Gen2                          1
Dimensity 9200 Plus                         1
Snapdragon 7s Gen 3                         1
Bionic A18 Pro                              1
Tiger T616                                  1
Snapdragon 8 Elite Gen5                     1
Unisoc T615                                 1
Snapdragon 4 Gen1                           1
Exynos 2100                                 1
Dimensity 7200                              1
Dimensity 8300 Ultra                        1
Snapdragon 7 Gen1 AE                        1
Snapdragon 4 Gen 2 AE                       1
Helio G37                                   1
Dimensity 7300X                             1
Helio P22                                   1
Unisoc 9863A                                1
Snapdragon 8 Gen 3                          1
MediaTek Cortex-A7                          1
Dimensity 8100                              1
Dimensity 8100 Max                          1
Dimensity 8200                              1
Dimensity 8020                              1
Helio G70                                   1
Dimensity 8100-Max                          1
Unisoc UMS9230E                             1
Helio G95                                   1
Snapdragon 870                              1
Unisoc 9863a                                1
Snapdragon 660                              1
Snapdragon 720G                             1
MediaTek MTK6739                            1
Unisoc SC9863A1                             1
Dimensity 7300 E                            1
Helio G36                                   1
Snapdragon 7+ Gen2                          1
Qualcomm Snapdragon 625                     1
Exynos 7904                                 1
Exynos 7870                                 1
Dimensity 900                               1
Tiger T616                                  1
Snapdragon 778G+                            1
Snapdragon 778G                             1
Exynos 850                                  1
Snapdragon 865                              1
Dimensity 1200                              1
Snapdragon 460                              1
Helio G35                                   1
Helio G25                                   1
Snapdragon 710                              1
Snapdragon 439                              1
Snapdragon 625                              1
UNISOC 9863a                                1
Helio 6739                                  1
MediaTek Helio G81                          1
Name: count, dtype: int64

In [548]:
temp_df = df1[df1['Processor Name'].str.contains('Core')][['Processor Name','Number of Cores','Processor Speed']].shift(1,axis=1)

In [549]:
df1.loc[temp_df.index,['Processor Name','Number of Cores','Processor Speed']] = temp_df.values

In [569]:
df1[df1['Name'] == 'MTR M17 Max']

,index,Brand Name,Name,Price,Spec Score,SIM,Has 5G,Has NFC,Has IR Blaster,Processor,Processor Name,Number of Cores,Processor Speed,RAM,Battery,Display,Camera,Memory Card,OS
658,676,mtr,MTR M17 Max,9600,25,"Dual Sim, 4G, Wi-Fi",False,False,False,512 MHz Processor,MediaTek Cortex-A7,Quad Core Processor,512 MHz Processor,"3 GB RAM, 32 GB inbuilt",5000 mAh Battery,"6.5 inches, 320 x 480 px Display with Punch Hole",8 MP Rear Camera,Memory Card Not Supported,NaN

In [538]:
temp_df = df1[df1['Processor Name'] == 'Dual Core Processor']

In [565]:
df1.loc[658,'Processor Name'] = 'MediaTek Cortex-A7'

In [525]:
temp_df = df1[df1['Processor Name'].isnull()]

In [559]:
df1.loc[756,'Processor Name'] = 'Not Available'

In [574]:
processor_brand = df1['Processor Name'].str.split(' ').str.get(0).str.lower()

In [575]:
df1.insert(10,'Processor Brand',processor_brand)

In [576]:
df1.head()

,index,Brand Name,Name,Price,Spec Score,SIM,Has 5G,Has NFC,Has IR Blaster,Processor,Processor Brand,Processor Name,Number of Cores,Processor Speed,RAM,Battery,Display,Camera,Memory Card,OS
0,0,vivo,Vivo V80 5G,62999,84,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster",True,True,True,"Snapdragon 7 Gen4, Octa Core, 2.8 GHz Processor",snapdragon,Snapdragon 7 Gen4,Octa Core,2.8 GHz Processor,"8 GB RAM, 128 GB inbuilt",7200 mAh Battery with 90W Fast Charging,"6.59 inches, 1260 x 2750 px, 144 Hz Display wi...",50 MP + 50 MP + 8 MP Triple Rear & 50 MP Front...,Memory Card Not Supported,Android v17
1,1,samsung,Samsung Galaxy S25 Ultra,99999,92,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi",True,True,False,"Snapdragon 8 Elite for Galaxy, Octa Core, 4.47...",snapdragon,Snapdragon 8 Elite for Galaxy,Octa Core,4.47 GHz Processor,"12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 45W Fast Charging,"6.9 inches, 1440 x 3120 px, 120 Hz Display wit...",200 MP Quad Rear & 12 MP Front Camera,Memory Card Not Supported,Android v15
2,2,samsung,Samsung Galaxy S23 5G,49999,74,"Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi",True,True,False,"Snapdragon 8 Gen 2, Octa Core, 3.36 GHz Processor",snapdragon,Snapdragon 8 Gen 2,Octa Core,3.36 GHz Processor,"8 GB RAM, 128 GB inbuilt",3900 mAh Battery with 25W Fast Charging,"6.1 inches, 1080 x 2340 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,NaN
3,3,motorola,Motorola Edge 70 Fusion,29299,70,"Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi",True,True,False,"Snapdragon 7s Gen4, Octa Core, 2.7 GHz Processor",snapdragon,Snapdragon 7s Gen4,Octa Core,2.7 GHz Processor,"8 GB RAM, 128 GB inbuilt",7000 mAh Battery with 68W Fast Charging,"6.8 inches, 1272 x 2772 px, 144 Hz Display wit...",50 MP + 13 MP + Dedicated 3-in-1 light sensor ...,Memory Card Not Supported,NaN
4,4,oppo,OPPO K14 Plus 5G,29999,67,"Dual Sim, 5G, VoLTE, Wi-Fi, IR Blaster",True,False,True,"Dimensity 7360 Max, Octa Core, 2.5 GHz Processor",dimensity,Dimensity 7360 Max,Octa Core,2.5 GHz Processor,"6 GB RAM, 128 GB inbuilt",8000 mAh Battery with 45W Fast Charging,"6.78 inches, 1272 x 2772 px, 144 Hz Display wi...",50 MP + 2 MP Dual Rear & 16 MP Front Camera,Memory Card Not Supported,Android v16

In [579]:
df1['Number of Cores'] = df1['Number of Cores'].str.strip()

In [597]:
df1['Number of Cores'].value_counts()

Number of Cores
Octa Core      837
Hexa Core       36
Deca Core       18
Single Core      9
Quad Core        5
Dual Core        4
Nine Core        3
Name: count, dtype: int64

In [583]:
df1['Number of Cores'] = df1['Number of Cores'].str.replace('Octa Core Processor','Octa Core').str.replace('Hexa Core Processor','Hexa Core').str.replace('Single Core Processor','Single Core').str.replace('Dual Core Processor','Dual Core').str.replace('Quad Core Processor','Quad Core').str.replace('Nine-Cores','Nine Core').str.replace('Nine Cores','Nine Core')

In [595]:
df1.loc[257,'Number of Cores'] = 'Quad Core'

In [601]:
df1[df1['Number of Cores'].isnull()]

,index,Brand Name,Name,Price,Spec Score,SIM,Has 5G,Has NFC,Has IR Blaster,Processor,Processor Brand,Processor Name,Number of Cores,Processor Speed,RAM,Battery,Display,Camera,Memory Card,OS
95,95,google,Google Pixel 11,82138,74,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi",True,True,False,Tensor G6,tensor,Tensor G6,NaN,NaN,"12 GB RAM, 256 GB inbuilt",4985 mAh Battery with 30W Fast Charging,"6.3 inches, 1080 x 2424 px, 120 Hz Display wit...",48 MP + 13 MP + 10.8 MP Triple Rear & 10.5 MP ...,Memory Card Not Supported,NaN
226,228,google,Google Pixel 11 Pro,119999,85,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi",True,True,False,Tensor G6,tensor,Tensor G6,NaN,NaN,"12 GB RAM, 256 GB inbuilt",4850 mAh Battery with Fast Charging,"6.3 inches, 1280 x 2856 px, 120 Hz Display wit...",50 MP + 48 MP + 48 MP Triple Rear & 42 MP Fron...,Memory Card Not Supported,NaN
361,369,google,Google Pixel 11 Pro XL,134999,83,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi",True,True,False,Tensor G6,tensor,Tensor G6,NaN,NaN,"12 GB RAM, 256 GB inbuilt",5115 mAh Battery with Fast Charging,"6.8 inches, 1344 x 2992 px, 120 Hz Display wit...",50 MP + 48 MP + 48 MP Triple Rear & 42 MP Fron...,Memory Card Not Supported,NaN
537,553,ringme,Ringme Bold S180 Air,9999,32,"Dual Sim, 4G, VoLTE, Wi-Fi",False,False,False,None,mediatek,MediaTek MT6739,None,None,"6 GB RAM, 64 GB inbuilt",4800 mAh Battery,"6.51 inches, 1440 x 720 px Display",16 MP Rear & 8 MP Front Camera,"Memory Card Supported, upto 256 GB",Android v12
562,578,google,Google Pixel 11 Pro (16GB RAM + 512GB),134999,86,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi",True,True,False,Tensor G6,tensor,Tensor G6,NaN,NaN,"16 GB RAM, 512 GB inbuilt",4850 mAh Battery with Fast Charging,"6.3 inches, 1280 x 2856 px, 120 Hz Display wit...",50 MP + 48 MP + 48 MP Triple Rear & 42 MP Fron...,Memory Card Not Supported,NaN
563,579,google,Google Pixel 11 Pro XL (16GB RAM + 512GB),149999,84,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi",True,True,False,Tensor G6,tensor,Tensor G6,NaN,NaN,"16 GB RAM, 512 GB inbuilt",5115 mAh Battery with Fast Charging,"6.8 inches, 1344 x 2992 px, 120 Hz Display wit...",50 MP + 48 MP + 48 MP Triple Rear & 42 MP Fron...,Memory Card Not Supported,NaN
564,580,google,Google Pixel 11 Pro Fold,186999,86,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi",True,True,False,Tensor G6,tensor,Tensor G6,NaN,NaN,"16 GB RAM, 512 GB inbuilt",4806 mAh Battery with Fast Charging,"8 inches, 2076 x 2152 px, 120 Hz Display with ...",48 MP + 10.8 MP + 10.5 MP Triple Rear & 10 MP ...,Memory Card Not Supported,Android v17
565,581,google,Google Pixel 11 5G (12GB RAM + 512GB),104999,75,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi",True,True,False,Tensor G6,tensor,Tensor G6,NaN,NaN,"12 GB RAM, 512 GB inbuilt",4985 mAh Battery with 30W Fast Charging,"6.3 inches, 1080 x 2424 px, 120 Hz Display wit...",48 MP + 13 MP + 10.8 MP Triple Rear & 10.5 MP ...,Memory Card Not Supported,NaN
660,678,lava,Lava Virat V1 4G,9899,40,"Dual Sim, 4G, VoLTE, Wi-Fi",False,False,False,Unisoc 9863a,unisoc,Unisoc 9863a,NaN,NaN,"4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 10W Fast Charging,"6.75 inches, 720 x 1600 px, 90 Hz Display with...",13 MP Dual Rear & 5 MP Front Camera,"Memory Card (Hybrid), upto 256 GB",Android 15 Go
813,854,peace,Peace i17 Air,9499,27,"Dual Sim, 4G, VoLTE, Wi-Fi",False,False,False,None,mediatek,MediaTek MT6739,None,None,None,5000 mAh Battery,"6.56 inches, 1640 x 720 px Display",20 MP Rear & 8 MP Front Camera,"Memory Card Supported, upto 128 GB",Android v14.0
919,1007,peace,Peace Nova 11 4G,7999,26,"Dual Sim, 4G, Wi-Fi",False,False,False,Helio 6739,helio,Helio 6739,NaN,NaN,"4 GB RAM, 64 GB inbuilt",2000 mAh Battery,6.56 inches Display,20 MP Rear & 5 MP Front Camera,"Memory Card Supported, upto 128 GB",NaN

In [629]:
df1['Processor Speed'].value_counts()

Processor Speed
2.4000    233
2.5000     78
2.2000     66
2.6000     63
2.0000     38
2.3000     31
1.8000     31
3.2000     29
2.8000     28
3.0000     28
2.7000     21
3.8000     18
3.3500     16
2.8400     15
3.4000     12
3.3000     12
3.2500     10
4.6000     10
4.4700      9
4.7400      9
4.9300      8
2.6300      6
4.3200      6
2.9000      6
2.8500      6
3.1000      6
3.3600      5
4.0400      5
1.6000      5
3.6300      4
3.7800      4
4.2100      4
3.7300      4
2.0500      4
0.5100      4
1.7000      3
3.4600      3
3.1100      2
2.9600      2
2.3600      2
2.3900      2
0.0013      2
3.8400      1
4.0500      1
3.3900      1
1.0000      1
2.9100      1
2.1000      1
Name: count, dtype: int64

In [618]:
df1.loc[temp_df.index,'Processor Speed'] = '0.0013 GHz Processor'

In [608]:
df1['Processor Speed'] = df1['Processor Speed'].str.strip()

In [628]:
df1['Processor Speed'] = df1['Processor Speed'].str.split().str.get(0).astype(float)

In [630]:
df1['Processor Speed'].isnull().sum()

np.int64(67)

In [631]:
df1['Processor Name'].isnull().sum()

np.int64(0)

In [639]:
df1[df1['Number of Cores'].isnull()]

,index,Brand Name,Name,Price,Spec Score,SIM,Has 5G,Has NFC,Has IR Blaster,Processor,Processor Brand,Processor Name,Number of Cores,Processor Speed,RAM,Battery,Display,Camera,Memory Card,OS
95,95,google,Google Pixel 11,82138,74,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi",True,True,False,Tensor G6,tensor,Tensor G6,NaN,NaN,12,4985 mAh Battery with 30W Fast Charging,"6.3 inches, 1080 x 2424 px, 120 Hz Display wit...",48 MP + 13 MP + 10.8 MP Triple Rear & 10.5 MP ...,Memory Card Not Supported,NaN
226,228,google,Google Pixel 11 Pro,119999,85,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi",True,True,False,Tensor G6,tensor,Tensor G6,NaN,NaN,12,4850 mAh Battery with Fast Charging,"6.3 inches, 1280 x 2856 px, 120 Hz Display wit...",50 MP + 48 MP + 48 MP Triple Rear & 42 MP Fron...,Memory Card Not Supported,NaN
361,369,google,Google Pixel 11 Pro XL,134999,83,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi",True,True,False,Tensor G6,tensor,Tensor G6,NaN,NaN,12,5115 mAh Battery with Fast Charging,"6.8 inches, 1344 x 2992 px, 120 Hz Display wit...",50 MP + 48 MP + 48 MP Triple Rear & 42 MP Fron...,Memory Card Not Supported,NaN
537,553,ringme,Ringme Bold S180 Air,9999,32,"Dual Sim, 4G, VoLTE, Wi-Fi",False,False,False,None,mediatek,MediaTek MT6739,None,NaN,6,4800 mAh Battery,"6.51 inches, 1440 x 720 px Display",16 MP Rear & 8 MP Front Camera,"Memory Card Supported, upto 256 GB",Android v12
562,578,google,Google Pixel 11 Pro (16GB RAM + 512GB),134999,86,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi",True,True,False,Tensor G6,tensor,Tensor G6,NaN,NaN,16,4850 mAh Battery with Fast Charging,"6.3 inches, 1280 x 2856 px, 120 Hz Display wit...",50 MP + 48 MP + 48 MP Triple Rear & 42 MP Fron...,Memory Card Not Supported,NaN
563,579,google,Google Pixel 11 Pro XL (16GB RAM + 512GB),149999,84,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi",True,True,False,Tensor G6,tensor,Tensor G6,NaN,NaN,16,5115 mAh Battery with Fast Charging,"6.8 inches, 1344 x 2992 px, 120 Hz Display wit...",50 MP + 48 MP + 48 MP Triple Rear & 42 MP Fron...,Memory Card Not Supported,NaN
564,580,google,Google Pixel 11 Pro Fold,186999,86,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi",True,True,False,Tensor G6,tensor,Tensor G6,NaN,NaN,16,4806 mAh Battery with Fast Charging,"8 inches, 2076 x 2152 px, 120 Hz Display with ...",48 MP + 10.8 MP + 10.5 MP Triple Rear & 10 MP ...,Memory Card Not Supported,Android v17
565,581,google,Google Pixel 11 5G (12GB RAM + 512GB),104999,75,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi",True,True,False,Tensor G6,tensor,Tensor G6,NaN,NaN,12,4985 mAh Battery with 30W Fast Charging,"6.3 inches, 1080 x 2424 px, 120 Hz Display wit...",48 MP + 13 MP + 10.8 MP Triple Rear & 10.5 MP ...,Memory Card Not Supported,NaN
660,678,lava,Lava Virat V1 4G,9899,40,"Dual Sim, 4G, VoLTE, Wi-Fi",False,False,False,Unisoc 9863a,unisoc,Unisoc 9863a,NaN,NaN,4,5000 mAh Battery with 10W Fast Charging,"6.75 inches, 720 x 1600 px, 90 Hz Display with...",13 MP Dual Rear & 5 MP Front Camera,"Memory Card (Hybrid), upto 256 GB",Android 15 Go
813,854,peace,Peace i17 Air,9499,27,"Dual Sim, 4G, VoLTE, Wi-Fi",False,False,False,None,mediatek,MediaTek MT6739,None,NaN,None,5000 mAh Battery,"6.56 inches, 1640 x 720 px Display",20 MP Rear & 8 MP Front Camera,"Memory Card Supported, upto 128 GB",Android v14.0
919,1007,peace,Peace Nova 11 4G,7999,26,"Dual Sim, 4G, Wi-Fi",False,False,False,Helio 6739,helio,Helio 6739,NaN,NaN,4,2000 mAh Battery,6.56 inches Display,20 MP Rear & 5 MP Front Camera,"Memory Card Supported, upto 128 GB",NaN

In [642]:
df1 = pd.read_csv('smartphones_cleaned_thirdphase_restored.csv')

In [646]:
df1['RAM'].isnull().sum()

np.int64(1)

In [647]:
ram_capacity = df1['RAM'].str.strip().str.split(',').str.get(0).str.split(' ').str.get(0)

In [652]:
df1.insert(15, 'RAM Capacity',ram_capacity)

In [662]:
df1.head(2)

,index,Brand Name,Name,Price,Spec Score,SIM,Has 5G,Has NFC,Has IR Blaster,Processor,...,Number of Cores,Processor Speed,RAM,RAM Capacity,ROM Capacity,Battery,Display,Camera,Memory Card,OS
0,0,vivo,Vivo V80 5G,62999,84,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster",True,True,True,"Snapdragon 7 Gen4, Octa Core, 2.8 GHz Processor",...,Octa Core,2.80,"8 GB RAM, 128 GB inbuilt",8,128,7200 mAh Battery with 90W Fast Charging,"6.59 inches, 1260 x 2750 px, 144 Hz Display wi...",50 MP + 50 MP + 8 MP Triple Rear & 50 MP Front...,Memory Card Not Supported,Android v17
1,1,samsung,Samsung Galaxy S25 Ultra,99999,92,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi",True,True,False,"Snapdragon 8 Elite for Galaxy, Octa Core, 4.47...",...,Octa Core,4.47,"12 GB RAM, 256 GB inbuilt",12,256,5000 mAh Battery with 45W Fast Charging,"6.9 inches, 1440 x 3120 px, 120 Hz Display wit...",200 MP Quad Rear & 12 MP Front Camera,Memory Card Not Supported,Android v15

In [660]:
rom_capacity = df1['RAM'].str.strip().str.split(',').str.get(1).str.strip().str.split(' ').str.get(0)

In [661]:
df1.insert(16, 'ROM Capacity',rom_capacity)

In [704]:
df1['ROM Capacity'] = df1['ROM Capacity'].astype(float)

In [705]:
df1['RAM Capacity'] = df1['RAM Capacity'].astype(float)

In [710]:
df1['ROM Capacity'].isnull().sum()

np.int64(0)

In [711]:
df1['RAM Capacity'].isnull().sum()

np.int64(0)

In [772]:
battery_capacity = df1['Battery'].str.strip().str.split('with').str.get(0).str.split(' ').str.get(0)

In [773]:
fast_charging = df1['Battery'].str.strip().str.split('with').str.get(1).str.strip().str.split(' ').str.get(0)

In [779]:
df1.insert(17, 'Battery Capacity',battery_capacity)
df1.insert(18, 'Fast Charging',fast_charging)

In [780]:
df1['Fast Charging'] = df1['Fast Charging'].str.replace('W', '')

In [813]:
df1.head(2)

,index,Brand Name,Name,Price,Spec Score,SIM,Has 5G,Has NFC,Has IR Blaster,Processor,...,Battery Capacity,Fast Charging,Battery,Display,Screen Size,Resolution,Refresh Rate,Camera,Memory Card,OS
0,0,vivo,Vivo V80 5G,62999,84,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster",True,True,True,"Snapdragon 7 Gen4, Octa Core, 2.8 GHz Processor",...,7200,90,7200 mAh Battery with 90W Fast Charging,"6.59 inches, 1260 x 2750 px, 144 Hz Display wi...",6.59,1260 x 2750,144,50 MP + 50 MP + 8 MP Triple Rear & 50 MP Front...,Memory Card Not Supported,Android v17
1,1,samsung,Samsung Galaxy S25 Ultra,99999,92,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi",True,True,False,"Snapdragon 8 Elite for Galaxy, Octa Core, 4.47...",...,5000,45,5000 mAh Battery with 45W Fast Charging,"6.9 inches, 1440 x 3120 px, 120 Hz Display wit...",6.90,1440 x 3120,120,200 MP Quad Rear & 12 MP Front Camera,Memory Card Not Supported,Android v15

In [782]:
df1['Battery'].value_counts()

Battery
5000 mAh Battery with 25W Fast Charging      55
7000 mAh Battery with 80W Fast Charging      37
5000 mAh Battery with 45W Fast Charging      37
5000 mAh Battery with 33W Fast Charging      26
8000 mAh Battery with 45W Fast Charging      21
6500 mAh Battery with 45W Fast Charging      19
5000 mAh Battery with 10W Fast Charging      18
6000 mAh Battery with 45W Fast Charging      18
5000 mAh Battery with 18W Fast Charging      18
7000 mAh Battery with 15W Fast Charging      17
6000 mAh Battery with 25W Fast Charging      17
5000 mAh Battery with 67W Fast Charging      17
6000 mAh Battery with 33W Fast Charging      16
6000 mAh Battery with 18W Fast Charging      16
6500 mAh Battery with 44W Fast Charging      15
7000 mAh Battery with 45W Fast Charging      14
6000 mAh Battery with 80W Fast Charging      14
6500 mAh Battery with 90W Fast Charging      14
6300 mAh Battery with 15W Fast Charging      13
7200 mAh Battery with 44W Fast Charging      11
7000 mAh Battery with 120W Fast Charging     11
6000 mAh Battery with 15W Fast Charging      11
7000 mAh Battery with 60W Fast Charging      11
5000 mAh Battery                             10
5000 mAh Battery with 80W Fast Charging      10
8000 mAh Battery with 80W Fast Charging      10
4000 mAh Battery with 25W Fast Charging      10
7050 mAh Battery with 44W Fast Charging      10
5000 mAh Battery with 15W Fast Charging       9
7000 mAh Battery with 30W Fast Charging       8
6000 mAh Battery with 90W Fast Charging       8
4900 mAh Battery with 45W Fast Charging       7
7000 mAh Battery with 33W Fast Charging       7
4400 mAh Battery with 25W Fast Charging       7
5200 mAh Battery with 15W Fast Charging       7
6000 mAh Battery with Fast Charging           6
5000 mAh Battery with 68W Fast Charging       6
2000 mAh Battery                              6
5400 mAh Battery with 50W Fast Charging       6
5000 mAh Battery with Fast Charging           6
4500 mAh Battery with 65W Fast Charging       6
4300 mAh Battery with 25W Fast Charging       6
4500 mAh Battery with 25W Fast Charging       5
5520 mAh Battery with 45W Fast Charging       5
10001 mAh Battery with 80W Fast Charging      5
9000 mAh Battery with 67W Fast Charging       5
6500 mAh Battery with 80W Fast Charging       5
6500 mAh Battery with 100W Fast Charging      5
5500 mAh Battery with 45W Fast Charging       5
5800 mAh Battery with 45W Fast Charging       5
4056 mAh Battery with Fast Charging           4
5700 mAh Battery with 44W Fast Charging       4
4832 mAh Battery with Fast Charging           4
7900 mAh Battery with 45W Fast Charging       4
10000 mAh Battery with 100W Fast Charging     4
5391 mAh Battery with Fast Charging           4
5160 mAh Battery with 18W Fast Charging       4
4000 mAh Battery                              4
4005 mAh Battery with Fast Charging           4
5800 mAh Battery with Fast Charging           4
7000 mAh Battery with 68W Fast Charging       4
6500 mAh Battery with 15W Fast Charging       4
5000 mAh Battery with 90W Fast Charging       4
6000 mAh Battery with 10W Fast Charging       4
5100 mAh Battery with 45W Fast Charging       4
5100 mAh Battery with 67W Fast Charging       3
5000 mAh Battery with 100W Fast Charging      3
3149 mAh Battery with Fast Charging           3
7025 mAh Battery with 80W Fast Charging       3
4800 mAh Battery with 45W Fast Charging       3
5200 mAh Battery with 18W Fast Charging       3
5000 mAh Battery with 66W Fast Charging       3
5000 mAh Battery with 120W Fast Charging      3
7200 mAh Battery with 90W Fast Charging       3
3900 mAh Battery with 25W Fast Charging       3
7600 mAh Battery with 100W Fast Charging      3
5850 mAh Battery with 80W Fast Charging       3
6700 mAh Battery with 80W Fast Charging       3
3988 mAh Battery with Fast Charging           3
5000 mAh Battery with 60W Fast Charging       3
7000 mAh Battery with 90W Fast Charging       3
6200 mAh Battery with 80W Fast Charging       3
4500 mAh Battery with 33W Fast Charging       3
3700 mAh Battery with 25W Fast Charging       3
10000 mAh Battery with 44W Fast Charging      2
9000 mAh Battery with 80W Fast Charging       2
6800 mAh Battery with 80W Fast Charging       2
5800 mAh Battery with 80W Fast Charging       2
5000 mAh Battery with 30W Fast Charging       2
5600 mAh Battery with 80W Fast Charging       2
5200 mAh Battery with 45W Fast Charging       2
8000 mAh Battery with Fast Charging           2
4500 mAh Battery with 45W Fast Charging       2
5500 mAh Battery with 120W Fast Charging      2
4355 mAh Battery with 30W Fast Charging       2
6500 mAh Battery with 67W Fast Charging       2
7100 mAh Battery with 90W Fast Charging       2
4500 mAh Battery with 125W Fast Charging      2
4600 mAh Battery with 120W Fast Charging      2
3800 mAh Battery with 30W Fast Charging       2
4250 mAh Battery with 33W Fast Charging       2
4985 mAh Battery with 30W Fast Charging       2
7300 mAh Battery with 120W Fast Charging      2
7000 mAh Battery with 100W Fast Charging      2
5110 mAh Battery with 45W Fast Charging       2
5200 mAh Battery with 90W Fast Charging       2
5200 mAh Battery with 80W Fast Charging       2
4700 mAh Battery with 25W Fast Charging       2
9020 mAh Battery with 90W Fast Charging       2
5500 mAh Battery with 100W Fast Charging      2
6200 mAh Battery with 90W Fast Charging       2
5500 mAh Battery with 65W Fast Charging       2
7400 mAh Battery with 80W Fast Charging       2
3349 mAh Battery with Fast Charging           2
6580 mAh Battery with 45W Fast Charging       2
9000 mAh Battery with 100W Fast Charging      2
7540 mAh Battery with 100W Fast Charging      2
5630 mAh Battery with 80W Fast Charging       2
5160 mAh Battery with 67W Fast Charging       2
4700 mAh Battery with 67W Fast Charging       2
5700 mAh Battery with 18W Fast Charging       2
4830 mAh Battery with 66W Fast Charging       2
6000 mAh Battery with 20W Fast Charging       2
4200 mAh Battery with 30W Fast Charging       2
4600 mAh Battery with 80W Fast Charging       2
5500 mAh Battery with 80W Fast Charging       2
5115 mAh Battery with Fast Charging           2
4674 mAh Battery with Fast Charging           2
4850 mAh Battery with Fast Charging           2
5000 mAh Battery with 65W Fast Charging       2
6040 mAh Battery with 90W Fast Charging       1
6330 mAh Battery with 100W Fast Charging      1
3692 mAh Battery with Fast Charging           1
4492 mAh Battery with Fast Charging           1
6720 mAh Battery with 33W Fast Charging       1
6600 mAh Battery with 100W Fast Charging      1
4970 mAh Battery with 30W Fast Charging       1
4383 mAh Battery with Fast Charging           1
5000 mAh Battery with 50W Fast Charging       1
6900 mAh Battery with 80W Fast Charging       1
7100 mAh Battery with 80W Fast Charging       1
7300 mAh Battery with 90W Fast Charging       1
5100 mAh Battery with 30W Fast Charging       1
3561 mAh Battery with Fast Charging           1
7550 mAh Battery with 90W Fast Charging       1
5500 mAh Battery with 68W Fast Charging       1
5100 mAh Battery with 23W Fast Charging       1
4685 mAh Battery with Fast Charging           1
5500 mAh Battery with 33W Fast Charging       1
5000 mAh Battery with 44W Fast Charging       1
4870 mAh Battery with 30W Fast Charging       1
5010 mAh Battery with 33W Fast Charging       1
4614 mAh Battery with 30W Fast Charging       1
4610 mAh Battery with 90W Fast Charging       1
5240 mAh Battery with 90W Fast Charging       1
7000 mAh Battery                              1
5600 mAh Battery with 90W Fast Charging       1
5030 mAh Battery with 33W Fast Charging       1
4410 mAh Battery with Fast Charging           1
4700 mAh Battery with 27W Fast Charging       1
3300 mAh Battery with 15W Fast Charging       1
6510 mAh Battery with 90W Fast Charging       1
4575 mAh Battery with 30W Fast Charging       1
7050 mAh Battery with 100W Fast Charging      1
4385 mAh Battery with 18W Fast Charging       1
5200 mAh Battery with 20W Fast Charging       1
6000 mAh Battery with 100W Fast Charging      1
5050 mAh Battery with 30W Fast Charging       1
4806 mAh Battery with Fast Charging           1
4000 mAh Battery with 30W Fast Charging       1
4800 mAh Battery with 44W Fast Charging       1
5500 mAh Battery with 15W Fast Charging       1
5910 mAh Battery with 80W Fast Charging       1
3900 mAh Battery                              1
5080 mAh Battery with 67W Fast Charging       1
4400 mAh Battery with 68W Fast Charging       1
4700 mAh Battery with 100W Fast Charging      1
4980 mAh Battery with 120W Fast Charging      1
4600 mAh Battery with 66W Fast Charging       1
4800 mAh Battery                              1
4200 mAh Battery with 65W Fast Charging       1
5700 mAh Battery with 100W Fast Charging      1
4325 mAh Battery with Fast Charging           1
5800 mAh Battery with 120W Fast Charging      1
5060 mAh Battery with 37W Fast Charging       1
4449 mAh Battery with 23W Fast Charging       1
4500 mAh Battery with 80W Fast Charging       1
4650 mAh Battery with Fast Charging           1
5015 mAh Battery with 30W Fast Charging       1
4500 mAh Battery with 66W Fast Charging       1
4700 mAh Battery with 66W Fast Charging       1
4520 mAh Battery with 33W Fast Charging       1
4500 mAh Battery with Fast Charging           1
3400 mAh Battery                              1
4300 mAh Battery with Fast Charging           1
4100 mAh Battery                              1
3000 mAh Battery                              1
3010 mAh Battery with Fast Charging           1
4800 mAh Battery with 150W Fast Charging      1
4500 mAh Battery with 60W Fast Charging       1
4020 mAh Battery with 33W Fast Charging       1
4500 mAh Battery with 120W Fast Charging      1
6000 mAh Battery                              1
4500 mAh Battery with 50W Fast Charging       1
5020 mAh Battery with 18W Fast Charging       1
4000 mAh Battery with 18W Fast Charging       1
3765 mAh Battery with 20W Fast Charging       1
3700 mAh Battery with 20W Fast Charging       1
3080 mAh Battery                              1
1821 mAh Battery with Fast Charging           1
2691 mAh Battery with Fast Charging           1
5200 mAh Battery with 10W Fast Charging       1
2000 mAh Battery with Fast Charging           1
Name: count, dtype: int64

In [783]:
df1['Fast Charging'].fillna(-1, inplace=True)

In [784]:
df1['Fast Charging'] = df1['Fast Charging'].replace('Fast', 0)

In [785]:
df1['Fast Charging'] = df1['Fast Charging'].astype(int)
df1['Battery Capacity'] = df1['Battery Capacity'].astype(int)

In [786]:
df1['Fast Charging'].value_counts()

Fast Charging
 45     150
 80     115
 25     108
 0       63
 15      63
 33      60
 90      47
 18      46
 44      44
 67      32
 100     29
-1       28
 30      26
 120     23
 10      23
 60      15
 68      12
 65      11
 50       8
 66       8
 20       5
 125      2
 23       2
 27       1
 37       1
 150      1
Name: count, dtype: int64

In [787]:
df1['Fast Charging'].isnull().sum()

np.int64(0)

In [788]:
df1['Battery Capacity'].isnull().sum()

np.int64(0)

In [815]:
screen_size = df1['Display'].str.strip().str.split(',').str.get(0).str.strip().str.split(' ').str.get(0).astype(float)
resolution = df1['Display'].str.strip().str.split(',').str.get(1).str.strip().str.split('px').str.get(0)
refresh_rate = df1['Display'].str.strip().str.split(',').str.get(2).str.strip().str.split(' ').str.get(0).astype(float)

In [804]:
df1.insert(21, 'Screen Size',screen_size)
df1.insert(22, 'Resolution',resolution)
df1.insert(23, 'Refresh Rate',refresh_rate)

In [806]:
df1['Screen Size'].isnull().sum()

np.int64(0)

In [827]:
df1['Resolution'].isnull().sum()

np.int64(0)

In [839]:
df1['Refresh Rate'] = df1['Refresh Rate'].astype(int)

In [840]:
df1['Refresh Rate'].value_counts()

Refresh Rate
120    607
144    131
90      92
60      84
165      9
Name: count, dtype: int64

In [841]:
df1['Refresh Rate'].isnull().sum()

np.int64(0)

In [835]:
temp_df = df1[df1['Refresh Rate'].isnull()]

In [836]:
df1.loc[temp_df.index,'Refresh Rate'] = 60

In [823]:
df1.loc[919,'Resolution'] = '1616 x 720'

In [846]:
df1['Camera'] = df1['Camera'].str.replace('\n', ' ', regex=False)

In [847]:
df1['Camera'].value_counts()

Camera
50 MP + 2 MP Dual Rear & 8 MP Front Camera                                                              56
50 MP + 8 MP Dual Rear & 32 MP Front Camera                                                             35
50 MP + 8 MP Dual Rear & 16 MP Front Camera                                                             31
50 MP + 2 MP Dual Rear & 16 MP Front Camera                                                             30
50 MP + 2 MP Dual Rear & 32 MP Front Camera                                                             29
50 MP Dual Rear & 8 MP Front Camera                                                                     29
50 MP + 50 MP + 8 MP Triple Rear & 50 MP Front Camera                                                   26
13 MP Rear & 5 MP Front Camera                                                                          26
50 MP Rear & 8 MP Front Camera                                                                          24
50 MP + 5 MP + 2 MP Triple Rear & 13 MP Front Camera                                                    17
50 MP + 50 MP + 50 MP Triple Rear & 32 MP Front Camera                                                  16
48 MP + 48 MP + 48 MP Triple Rear & 18 MP Front Camera                                                  15
50 MP + 8 MP + 2 MP Triple Rear & 13 MP Front Camera                                                    14
50 MP + 50 MP + 8 MP Triple Rear & 32 MP Front Camera                                                   14
50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front Camera                                                    13
8 MP Rear & 5 MP Front Camera                                                                           13
50 MP + 2 MP Dual Rear & 50 MP Front Camera                                                             12
50 MP + 12 MP + 10 MP Triple Rear & 12 MP Front Camera                                                  12
50 MP + 8 MP Dual Rear & 50 MP Front Camera                                                             11
50 MP + 8 MP Dual Rear & 20 MP Front Camera                                                             11
50 MP + 50 MP + 50 MP Triple Rear & 50 MP Front Camera                                                  11
50 MP + 0.08 MP Dual Rear & 5 MP Front Camera                                                           11
13 MP Dual Rear & 5 MP Front Camera                                                                     11
200 MP Quad Rear & 12 MP Front Camera                                                                   10
50 MP + 2 MP Dual Rear & 5 MP Front Camera                                                              10
13 MP Rear & 8 MP Front Camera                                                                          10
50 MP + 50 MP Dual Rear & 50 MP Front Camera                                                             9
64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front Camera                                                     9
50 MP + 8 MP + 2 MP Triple Rear & 50 MP Front Camera                                                     9
50 MP + 5 MP + 2 MP Triple Rear & 12 MP Front Camera                                                     9
108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front Camera                                                    8
50 MP + 48 MP + 48 MP Triple Rear & 42 MP Front Camera                                                   7
200 MP + 8 MP Dual Rear & 50 MP Front Camera                                                             7
50 MP + 12 MP Dual Rear & 10 MP Front Camera                                                             7
200 MP + 50 MP + 50 MP Triple Rear & 50 MP Front                       Camera                            7
32 MP Dual Rear & 8 MP Front Camera                                                                      7
20 MP Rear & 8 MP Front Camera                                                                           7
50 MP + 8 MP + 5 MP Triple Rear & 12 MP Front Camera                                                     6
50 MP + 2 MP Dual Rear & 20 MP Front Camera                                                              6
200 MP + 8 MP + 2 MP Triple Rear & 16 MP Front Camera                                                    6
50 MP + 8 MP + 2 MP Triple Rear & 20 MP Front Camera                                                     6
50 MP + 8 MP Dual Rear & 13 MP Front Camera                                                              6
48 MP + 12 MP Dual Rear & 12 MP Front Camera                                                             6
50 MP Dual Rear & 13 MP Front Camera                                                                     6
50 MP + Auxiliary lens Dual Rear & 8 MP Front Camera                                                     6
50 MP + 13 MP Dual Rear & 32 MP Front Camera                                                             6
64 MP + 8 MP + 2 MP Triple Rear & 32 MP Front Camera                                                     5
50 MP + 12 MP + 5 MP Triple Rear & 12 MP Front Camera                                                    5
50 MP + 12 MP + 8 MP Triple Rear & 12 MP Front Camera                                                    5
32 MP Rear & 8 MP Front Camera                                                                           5
50 MP Rear & 5 MP Front Camera                                                                           4
50 MP Dual Rear & 5 MP Front Camera                                                                      4
48 MP Rear & 12 MP Front Camera                                                                          4
50 MP + 13 MP + Dedicated 3-in-1 light sensor Triple Rear                       & 32 MP Front Camera     4
13 MP + 0.08 MP Dual Rear & 5 MP Front Camera                                                            4
48 MP + 48 MP Dual Rear & Under-display FaceTime                       Camera Front Camera               4
50 MP + 12 MP + 8 MP Triple Rear & 10 MP Front Camera                                                    4
50 MP + 32 MP + 8 MP Triple Rear & 32 MP Front Camera                                                    4
13 MP Rear Camera                                                                                        4
50 MP Quad Rear & 8 MP Front Camera                                                                      4
64 MP Quad Rear & 32 MP Front Camera                                                                     4
50 MP + 12 MP + 5 MP Triple Rear & 32 MP Front Camera                                                    4
48 MP Quad Rear & 16 MP Front Camera                                                                     4
64 MP Dual Rear & 8 MP Front Camera                                                                      3
50 MP + 50 MP Dual Rear & 32 MP Front Camera                                                             3
64 MP + 2 MP + 2 MP Triple Rear & 32 MP Front Camera                                                     3
50 MP + 12 MP + 10 MP Triple Rear & 4 MP Front Camera                                                    3
13 MP Dual Rear & 8 MP Front Camera                                                                      3
48 MP + 2 MP + 2 MP Triple Rear & 8 MP Front Camera                                                      3
200 MP + 50 MP + 10 MP Triple Rear & 10 MP Front                       Camera                            3
50 MP + 50 MP + 2 MP Triple Rear & 32 MP Front Camera                                                    3
48 MP Rear & 18 MP Front Camera                                                                          3
50 MP + 2 MP Dual Rear & 13 MP Front Camera                                                              3
12 MP + 12 MP + 8 MP Triple Rear & 32 MP Front Camera                                                    3
50 MP + 12 MP + 10 MP Triple Rear & 10 MP Front Camera                                                   3
50 MP + 8 MP + 2 MP Triple Rear & 32 MP Front Camera                                                     3
200 MP + 50 MP + 8 MP Triple Rear & 50 MP Front Camera                                                   3
50 MP Dual Rear & 16 MP Front Camera                                                                     3
8 MP Rear & 8 MP Front Camera                                                                            3
108 MP + 8 MP + 2 MP Triple Rear & 32 MP Front Camera                                                    3
50 MP + 48 MP + 32 MP Triple Rear & 16 MP Front Camera                                                   3
200 MP + 8 MP Dual Rear & 32 MP Front Camera                                                             3
48 MP + 13 MP + 10.8 MP Triple Rear & 10.5 MP Front                       Camera                         3
48 MP + 8 MP Dual Rear & 13 MP Front Camera                                                              3
200 MP + 50 MP + 50 MP Triple Rear & 32 MP Front                       Camera                            3
50 MP + 50 MP Dual Rear & 10 MP Front Camera                                                             3
50 MP + 50 MP + 10 MP Triple Rear & 50 MP Front Camera                                                   3
12 MP + 12 MP Dual Rear & 10 MP Front Camera                                                             3
48 MP + 13 MP Dual Rear & 13 MP Front Camera                                                             2
50 MP + 8 MP + 2 MP Triple Rear & 8 MP Front Camera                                                      2
50 MP + 50 MP + 12 MP Triple Rear & 32 MP + 32 MP Dual                       Front Camera                2
200 MP + 8 MP Dual Rear & 20 MP Front Camera                                                             2
50 MP + 50 MP + 8 MP Triple Rear & 20 MP Front Camera                                                    2
200 MP + 12 MP Dual Rear & 12 MP Front Camera                                                            2
50 MP + 50 MP + 8 MP Triple Rear & 16 MP Front Camera                                                    2
64 MP + 13 MP Dual Rear & 13 MP Front Camera                                                             2
64 MP + 2 MP Dual Rear & 13 MP Front Camera                                                              2
13 MP Quad Rear & 8 MP Front Camera                                                                      2
48 MP Quad Rear & 8 MP Front Camera                                                                      2
48 MP + 5 MP Dual Rear & 16 MP Front Camera                                                              2
50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front Camera                                                     2
48 MP Rear & 8 MP Front Camera                                                                           2
50 MP + 0.08 MP Dual Rear & 8 MP Front Camera                                                            2
32 MP + 2 MP Dual Rear & 8 MP Front Camera                                                               2
5 MP Rear & 2 MP Front Camera                                                                            2
50 MP + 8 MP + 2 MP Triple Rear & 12 MP Front Camera                                                     2
108 MP + 8 MP Dual Rear & 20 MP Front Camera                                                             2
50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 MP Dual                       Front Camera                 2
64 MP Quad Rear & 32 MP + 8 MP Dual Front Camera                                                         2
64 MP + 0.08 MP Dual Rear & 16 MP Front Camera                                                           2
50 MP + Depth Sensor Dual Rear & 8 MP Front Camera                                                       2
50 MP + 2 MP + 0.08 MP Triple Rear & 8 MP Front Camera                                                   2
50 MP + 50 MP + 12 MP Triple Rear & 32 MP Front Camera                                                   2
48 MP + 8 MP + 2 MP Triple Rear & 13 MP Front Camera                                                     2
48 MP + 8 MP + 5 MP Triple Rear & 13 MP Front Camera                                                     2
64 MP Quad Rear & 16 MP Front Camera                                                                     2
48 MP + 10.8 MP + 10.5 MP Triple Rear & 10 MP Front                       Camera                         2
50 MP + 12 MP Dual Rear & 10.8 MP Front Camera                                                           2
200 MP + 12 MP + 2 MP Triple Rear & 50 MP Front Camera                                                   2
200 MP + 12 MP + 10 MP Triple Rear & 10 MP Front                       Camera                            2
48 MP Quad Rear & 13 MP Front Camera                                                                     2
5 MP Rear Camera                                                                                         2
48 MP + 48 MP Dual Rear & 18 MP Front Camera                                                             1
50 MP + 8 MP Dual Rear & 8 MP Front Camera                                                               1
50 MP + 13 MP + 10 MP Triple Rear & 50 MP Front Camera                                                   1
200 MP + 200 MP + 50 MP Triple Rear & 50 MP Front                       Camera                           1
32 MP Rear & 5 MP Front Camera                                                                           1
200 MP + 50 MP + 50 MP Triple Rear & 20 MP Front                       Camera                            1
108 MP + 2 MP Triple Rear & 8 MP Front Camera                                                            1
50 MP + 8 MP + 5 MP Triple Rear & 13 MP Front Camera                                                     1
50 MP + 48 MP + 48 MP Triple Rear & 10.5 MP Front                       Camera                           1
48 MP + 48 MP + 12 MP Triple Rear & 12 MP Front Camera                                                   1
48 MP + 16 MP + 8 MP Triple Rear & 16 MP Front Camera                                                    1
16 MP Rear & 8 MP Front Camera                                                                           1
108 MP + Macro Dual Rear & 13 MP Front Camera                                                            1
50 MP + 12 MP Dual Rear & 8 MP Front Camera                                                              1
64 MP + 8 MP Dual Rear & 50 MP Front Camera                                                              1
108 MP Quad Rear & 40 MP Front Camera                                                                    1
12.2 MP + 12 MP Dual Rear & 8 MP Front Camera                                                            1
50 MP + 13 MP + 10 MP Triple Rear & 32 MP Front Camera                                                   1
50 MP + 12 MP Dual Rear & 10.5 MP Front Camera                                                           1
200 MP Penta Rear & 50 MP Front Camera                                                                   1
64 MP + 50 MP + 50 MP Triple Rear & 50 MP Front Camera                                                   1
50 MP + 48 MP Dual Rear & 10.5 MP Front Camera                                                           1
13 MP + 2 MP Dual Rear & 8 MP Front Camera                                                               1
108 MP + 2 MP Triple Rear & 16 MP Front Camera                                                           1
50 MP + 48 MP + 8 MP Triple Rear & 32 MP Front Camera                                                    1
64 MP + 2 MP Dual Rear & 16 MP Front Camera                                                              1
64 MP + 32 MP + 8 MP Triple Rear & 32 MP Front Camera                                                    1
50 MP + 2 MP Triple Rear & 16 MP Front Camera                                                            1
64 MP + 50 MP + 50 MP Triple Rear & 32 MP Front Camera                                                   1
8 MP Rear Camera                                                                                         1
50 MP + 5 MP Dual Rear & 8 MP Front Camera                                                               1
13 MP + 2 MP Dual Rear & 5 MP Front Camera                                                               1
20 MP Rear Camera                                                                                        1
48 MP + 10.8 MP + 10.5 MP Triple Rear & 10 MP + 10 MP                       Dual Front Camera            1
50 MP + 50 MP + 50 MP Triple Rear & 20 MP Front Camera                                                   1
64 MP + 2 MP Dual Rear & 8 MP Front Camera                                                               1
50 MP Quad Rear & 32 MP Front Camera                                                                     1
64 MP + 50 MP + 8 MP Triple Rear & 32 MP Front Camera                                                    1
108 MP Quad Rear & 32 MP Front Camera                                                                    1
48 MP + 13 MP + 2 MP Triple Rear & 16 MP Front Camera                                                    1
16 MP + 12 MP + 12 MP Triple Rear & 12 MP Front Camera                                                   1
64 MP + 13 MP Dual Rear & 32 MP Front Camera                                                             1
108 MP + 2 MP Dual Rear & 8 MP Front Camera                                                              1
108 MP + 8 MP + 5 MP Triple Rear & 20 MP Front Camera                                                    1
50 MP + 48 MP + 2 MP Triple Rear & 16 MP Front Camera                                                    1
64 MP Quad Rear & 20 MP Front Camera                                                                     1
48 MP + 16 MP + 2 MP Triple Rear & 16 MP Front Camera                                                    1
8 MP + 0.08 MP Dual Rear & 5 MP Front Camera                                                             1
13 MP + 12 MP Dual Rear & 32 MP Front Camera                                                             1
108 MP + 2 MP Dual Rear & 16 MP Front Camera                                                             1
64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front Camera                                                     1
13 MP + 5 MP + 5 MP Triple Rear & 16 MP Front Camera                                                     1
13 MP + 5 MP Dual Rear & 5 MP Front Camera                                                               1
20 MP + 12 MP Dual Rear & 20 MP Front Camera                                                             1
64 MP + 2 MP + 2 MP Triple Rear & 13 MP Front Camera                                                     1
64 MP + 8 MP + 5 MP Triple Rear & 20 MP Front Camera                                                     1
108 MP + 8 MP + 5 MP Triple Rear & 16 MP Front Camera                                                    1
48 MP + 2 MP + 2 MP Triple Rear & 16 MP Front Camera                                                     1
50 MP + 2 MP + 2 MP Triple Rear & 8 MP Front Camera                                                      1
64 MP + 8 MP + 5 MP Triple Rear & 16 MP Front Camera                                                     1
108 MP + 13 MP + 5 MP Triple Rear & 20 MP Front Camera                                                   1
12 MP + 2 MP Dual Rear & 8 MP Front Camera                                                               1
50 MP + 2 MP + 2 MP Triple Rear & 16 MP Front Camera                                                     1
48 MP + 16 MP + 12 MP Triple Rear & 16 MP Front Camera                                                   1

In [856]:
def camera_extractor(text):

    if 'Quad' in text:
        return '4'
    elif 'Triple' in text:
        return '3'
    elif 'Dual' in text:
        return '2'
    elif 'Missing' in text:
        return 'Missing'
    else:
        return 1

In [851]:
num_rear_cameras = df1['Camera'].str.strip().str.split('&').str.get(0).apply(camera_extractor)

In [874]:
primary_rear_camera = df1['Camera'].str.strip().str.split('&').str.get(0).str.strip().str.split(' ').str.get(0)

In [858]:
num_front_cameras = df1['Camera'].str.strip().str.split('&').str.get(1).str.strip().fillna('Missing').apply(camera_extractor)

In [886]:
primary_front_camera = df1['Camera'].str.strip().str.split('&').str.get(1).str.strip().str.split(' ').str.get(0)

In [915]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 923 entries, 0 to 922
Data columns (total 33 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   index                      923 non-null    int64
 1   Brand Name                 923 non-null    object
 2   Name                       923 non-null    object
 3   Price                      923 non-null    int64
 4   Spec Score                 923 non-null    int64
 5   SIM                        923 non-null    object
 6   Has 5G                     923 non-null    bool
 7   Has NFC                    923 non-null    bool
 8   Has IR Blaster             923 non-null    bool
 9   Processor                  921 non-null    object
 10  Processor Brand            923 non-null    object
 11  Processor Name             923 non-null    object
 12  Number of Cores            912 non-null    object
 13  Processor Speed            856 non-null    float64
 14  RAM                        922 non-null    object
 15  RAM Capacity               923 non-null    float64
 16  ROM Capacity               923 non-null    float64
 17  Battery Capacity           923 non-null    int64
 18  Fast Charging              923 non-null    int64
 19  Battery                    923 non-null    object
 20  Display                    923 non-null    object
 21  Screen Size                923 non-null    float64
 22  Resolution                 923 non-null    object
 23  Refresh Rate               923 non-null    int64
 24  Camera                     923 non-null    object
 25  Number of Rear Cameras     923 non-null    int64
 26  Number of Front Cameras    923 non-null    object
 27  Primary Rear Camera        923 non-null    object
 28  Primary Front Camera       915 non-null    object
 29  Memory Card                923 non-null    object
 30  Extended Memory Available  923 non-null    int64
 31  Extended Memory            328 non-null    float64
 32  OS                         665 non-null    object
dtypes: bool(3), float64(5), int64(8), object(17)
memory usage: 219.2+ KB

In [ ]:
df1.insert(25, 'Number of Rear Cameras',num_rear_cameras)

In [859]:
df1.insert(26, 'Number of Front Cameras',num_front_cameras)

In [ ]:
df1.insert(27, 'Primary Rear Camera',primary_rear_camera)

In [891]:
df1.insert(28, 'Primary Front Camera',primary_front_camera)

In [864]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.width', None)

In [914]:
df1.head(2)

,index,Brand Name,Name,Price,Spec Score,SIM,Has 5G,Has NFC,Has IR Blaster,Processor,Processor Brand,Processor Name,Number of Cores,Processor Speed,RAM,RAM Capacity,ROM Capacity,Battery Capacity,Fast Charging,Battery,Display,Screen Size,Resolution,Refresh Rate,Camera,Number of Rear Cameras,Number of Front Cameras,Primary Rear Camera,Primary Front Camera,Memory Card,Extended Memory Available,Extended Memory,OS
0,0,vivo,Vivo V80 5G,62999,84,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster",True,True,True,"Snapdragon 7 Gen4, Octa Core, 2.8 GHz Processor",snapdragon,Snapdragon 7 Gen4,Octa Core,2.80,"8 GB RAM, 128 GB inbuilt",8.0,128.0,7200,90,7200 mAh Battery with 90W Fast Charging,"6.59 inches, 1260 x 2750 px, 144 Hz Display with Punch\n Hole",6.59,1260 x 2750,144,50 MP + 50 MP + 8 MP Triple Rear & 50 MP Front Camera,3,1,50,50,Memory Card Not Supported,0,NaN,Android v17
1,1,samsung,Samsung Galaxy S25 Ultra,99999,92,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi",True,True,False,"Snapdragon 8 Elite for Galaxy, Octa Core, 4.47 GHz\n Processor",snapdragon,Snapdragon 8 Elite for Galaxy,Octa Core,4.47,"12 GB RAM, 256 GB inbuilt",12.0,256.0,5000,45,5000 mAh Battery with 45W Fast Charging,"6.9 inches, 1440 x 3120 px, 120 Hz Display with Punch Hole",6.90,1440 x 3120,120,200 MP Quad Rear & 12 MP Front Camera,4,1,200,12,Memory Card Not Supported,0,NaN,Android v15

In [894]:
def memory_card_maker(text):

    if text == 'Memory Card Not Supported':
        return 0
    else:
        return 1

In [898]:
df1['Memory Card'].value_counts()

Memory Card
Memory Card Not Supported             485
Memory Card (Hybrid), upto 1 TB       104
Memory Card (Hybrid), upto 2 TB        84
Memory Card (Hybrid)                   71
Memory Card Supported, upto 1 TB       64
Memory Card Supported                  39
Memory Card Supported, upto 2 TB       30
Memory Card Supported, upto 512 GB     12
Memory Card Supported, upto 256 GB     11
Memory Card (Hybrid), upto 1.5 TB       9
Memory Card (Hybrid), upto 128 GB       7
Memory Card Supported, upto 128 GB      3
Memory Card (Hybrid), upto 512 GB       2
Memory Card (Hybrid), upto 256 GB       1
Memory Card Supported, upto 64 GB       1
Name: count, dtype: int64

In [895]:
memory_card_available = df1['Memory Card'].apply(memory_card_maker)

In [896]:
memory_card_available.value_counts()

Memory Card
0    485
1    438
Name: count, dtype: int64

In [900]:
df1.insert(30, 'Extended Memory Available',memory_card_available)

In [912]:
extended_memory = df1['Memory Card'].str.strip().str.split('upto').str.get(1).str.strip().str.split(' ').str.get(0).astype(float)

In [913]:
df1.insert(31, 'Extended Memory',extended_memory)

In [929]:
df1['OS'].value_counts()

OS
android    633
missing    258
ios         32
Name: count, dtype: int64

In [920]:
df1[df1['OS'] == 'v60']

Empty DataFrame
Columns: [index, Brand Name, Name, Price, Spec Score, SIM, Has 5G, Has NFC, Has IR Blaster, Processor, Processor Brand, Processor Name, Number of Cores, Processor Speed, RAM, RAM Capacity, ROM Capacity, Battery Capacity, Fast Charging, Battery, Display, Screen Size, Resolution, Refresh Rate, Camera, Number of Rear Cameras, Number of Front Cameras, Primary Rear Camera, Primary Front Camera, Memory Card, Extended Memory Available, Extended Memory, OS]
Index: []

In [919]:
df1.loc[809,'OS'] = 'Android v14'

In [926]:
def os_extractor(text):

    if 'Android' in text:
        return 'android'
    elif 'iOS' in text:
        return 'ios'
    elif 'Missing' in text:  
        return 'missing' 
    else:
        return 'other'

In [928]:
df1['OS'] = df1['OS'].str.strip().fillna('Missing').apply(os_extractor)

In [950]:
df1.head(2)

,index,Brand Name,Name,Price,Spec Score,SIM,Has 5G,Has NFC,Has IR Blaster,Processor,Processor Brand,Processor Name,Number of Cores,Processor Speed,RAM,RAM Capacity,ROM Capacity,Battery Capacity,Fast Charging,Battery,Display,Screen Size,Resolution,Refresh Rate,Camera,Number of Rear Cameras,Number of Front Cameras,Primary Rear Camera,Primary Front Camera,Memory Card,Extended Memory Available,Extended Memory,OS
0,0,vivo,Vivo V80 5G,62999,84,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster",True,True,True,"Snapdragon 7 Gen4, Octa Core, 2.8 GHz Processor",snapdragon,Snapdragon 7 Gen4,8.0,2.80,"8 GB RAM, 128 GB inbuilt",8.0,128.0,7200,90,7200 mAh Battery with 90W Fast Charging,"6.59 inches, 1260 x 2750 px, 144 Hz Display with Punch\n Hole",6.59,1260 x 2750,144,50 MP + 50 MP + 8 MP Triple Rear & 50 MP Front Camera,3,1,50,50,Memory Card Not Supported,0,NaN,android
1,1,samsung,Samsung Galaxy S25 Ultra,99999,92,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi",True,True,False,"Snapdragon 8 Elite for Galaxy, Octa Core, 4.47 GHz\n Processor",snapdragon,Snapdragon 8 Elite for Galaxy,8.0,4.47,"12 GB RAM, 256 GB inbuilt",12.0,256.0,5000,45,5000 mAh Battery with 45W Fast Charging,"6.9 inches, 1440 x 3120 px, 120 Hz Display with Punch Hole",6.90,1440 x 3120,120,200 MP Quad Rear & 12 MP Front Camera,4,1,200,12,Memory Card Not Supported,0,NaN,android

In [951]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 923 entries, 0 to 922
Data columns (total 33 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   index                      923 non-null    int64
 1   Brand Name                 923 non-null    object
 2   Name                       923 non-null    object
 3   Price                      923 non-null    int64
 4   Spec Score                 923 non-null    int64
 5   SIM                        923 non-null    object
 6   Has 5G                     923 non-null    bool
 7   Has NFC                    923 non-null    bool
 8   Has IR Blaster             923 non-null    bool
 9   Processor                  921 non-null    object
 10  Processor Brand            923 non-null    object
 11  Processor Name             923 non-null    object
 12  Number of Cores            923 non-null    float64
 13  Processor Speed            856 non-null    float64
 14  RAM                        922 non-null    object
 15  RAM Capacity               923 non-null    float64
 16  ROM Capacity               923 non-null    float64
 17  Battery Capacity           923 non-null    int64
 18  Fast Charging              923 non-null    int64
 19  Battery                    923 non-null    object
 20  Display                    923 non-null    object
 21  Screen Size                923 non-null    float64
 22  Resolution                 923 non-null    object
 23  Refresh Rate               923 non-null    int64
 24  Camera                     923 non-null    object
 25  Number of Rear Cameras     923 non-null    int64
 26  Number of Front Cameras    923 non-null    object
 27  Primary Rear Camera        923 non-null    object
 28  Primary Front Camera       915 non-null    object
 29  Memory Card                923 non-null    object
 30  Extended Memory Available  923 non-null    int64
 31  Extended Memory            328 non-null    float64
 32  OS                         923 non-null    object
dtypes: bool(3), float64(6), int64(8), object(16)
memory usage: 219.2+ KB

In [952]:
df1.isna().sum()

index                          0
Brand Name                     0
Name                           0
Price                          0
Spec Score                     0
SIM                            0
Has 5G                         0
Has NFC                        0
Has IR Blaster                 0
Processor                      2
Processor Brand                0
Processor Name                 0
Number of Cores                0
Processor Speed               67
RAM                            1
RAM Capacity                   0
ROM Capacity                   0
Battery Capacity               0
Fast Charging                  0
Battery                        0
Display                        0
Screen Size                    0
Resolution                     0
Refresh Rate                   0
Camera                         0
Number of Rear Cameras         0
Number of Front Cameras        0
Primary Rear Camera            0
Primary Front Camera           8
Memory Card                    0
Extended Memory Available      0
Extended Memory              595
OS                             0
dtype: int64

In [944]:
df1['Number of Cores'].value_counts()

Number of Cores
Octa Core      840
Hexa Core       36
Deca Core       18
Single Core      9
Quad Core        7
Hepta Core       6
Dual Core        4
Nine Core        3
Name: count, dtype: int64

Hepta Core

'Google Pixel 11' , 'Google Pixel 11 Pro' , 'Google Pixel 11 Pro XL' , 'Google Pixel 11 Pro (16GB RAM + 512GB), 'Google Pixel 11 Pro Fold' ,  'Google Pixel 11 5G (12GB RAM + 512GB)'

Octa Core 

'Google Pixel 11 Pro XL (16GB RAM + 512GB)' , 'Lava Virat V1 4G' , 'Ringme Bold S180 Air'

Quad Core

'Peace i17 Air' , 'Peace Nova 11 4G'

In [942]:
df1.loc[[813,919],'Number of Cores'] = 'Quad Core'

In [943]:
df1[df1['Number of Cores'].isnull()]

Empty DataFrame
Columns: [index, Brand Name, Name, Price, Spec Score, SIM, Has 5G, Has NFC, Has IR Blaster, Processor, Processor Brand, Processor Name, Number of Cores, Processor Speed, RAM, RAM Capacity, ROM Capacity, Battery Capacity, Fast Charging, Battery, Display, Screen Size, Resolution, Refresh Rate, Camera, Number of Rear Cameras, Number of Front Cameras, Primary Rear Camera, Primary Front Camera, Memory Card, Extended Memory Available, Extended Memory, OS]
Index: []

In [945]:
def core_extractor(text):

    if 'Single Core' in text:
        return 1
    elif 'Dual Core' in text:
        return 2
    elif 'Quad Core' in text:
        return 4
    elif 'Octa Core' in text:
        return 8
    elif 'Hexa Core' in text:
        return 6
    elif 'Hepta Core' in text:
        return 9
    elif 'Nine Core' in text:
        return 9
    else:
        return 10

In [949]:
df1['Number of Cores'] = df1['Number of Cores'].apply(core_extractor).astype(float)

In [959]:
df1['Fast Charging'].value_counts()

Fast Charging
 45     150
 80     115
 25     108
 0       63
 15      63
 33      60
 90      47
 18      46
 44      44
 67      32
 100     29
-1       28
 30      26
 120     23
 10      23
 60      15
 68      12
 65      11
 50       8
 66       8
 20       5
 125      2
 23       2
 27       1
 37       1
 150      1
Name: count, dtype: int64

In [955]:
def fast_charging_extractor(integer):

    if integer >= 0:
        return 1
    else:
        return 0

In [956]:
fast_charging_available = df1['Fast Charging'].apply(fast_charging_extractor)

In [957]:
df1.insert(18, 'Fast Charging Available',fast_charging_available)

In [971]:
df1.head(2)

,index,Brand Name,Name,Price,Spec Score,SIM,Has 5G,Has NFC,Has IR Blaster,Processor,Processor Brand,Processor Name,Number of Cores,Processor Speed,RAM,RAM Capacity,ROM Capacity,Battery Capacity,Fast Charging Available,Fast Charging,Battery,Display,Screen Size,Resolution,Refresh Rate,Camera,Number of Rear Cameras,Number of Front Cameras,Primary Rear Camera,Primary Front Camera,Memory Card,Extended Memory Available,Extended Memory,OS
0,0,vivo,Vivo V80 5G,62999,84,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster",True,True,True,"Snapdragon 7 Gen4, Octa Core, 2.8 GHz Processor",snapdragon,Snapdragon 7 Gen4,8.0,2.80,"8 GB RAM, 128 GB inbuilt",8.0,128.0,7200,1,90.0,7200 mAh Battery with 90W Fast Charging,"6.59 inches, 1260 x 2750 px, 144 Hz Display with Punch\n Hole",6.59,1260 x 2750,144,50 MP + 50 MP + 8 MP Triple Rear & 50 MP Front Camera,3,1,50.0,50,Memory Card Not Supported,0,NaN,android
1,1,samsung,Samsung Galaxy S25 Ultra,99999,92,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi",True,True,False,"Snapdragon 8 Elite for Galaxy, Octa Core, 4.47 GHz\n Processor",snapdragon,Snapdragon 8 Elite for Galaxy,8.0,4.47,"12 GB RAM, 256 GB inbuilt",12.0,256.0,5000,1,45.0,5000 mAh Battery with 45W Fast Charging,"6.9 inches, 1440 x 3120 px, 120 Hz Display with Punch Hole",6.90,1440 x 3120,120,200 MP Quad Rear & 12 MP Front Camera,4,1,200.0,12,Memory Card Not Supported,0,NaN,android

In [964]:
df1 = pd.read_csv('smartphone_cleaned_fourthphase.csv')

In [968]:
df1.head(2)

,index,Brand Name,Name,Price,Spec Score,SIM,Has 5G,Has NFC,Has IR Blaster,Processor,Processor Brand,Processor Name,Number of Cores,Processor Speed,RAM,RAM Capacity,ROM Capacity,Battery Capacity,Fast Charging Available,Fast Charging,Battery,Display,Screen Size,Resolution,Refresh Rate,Camera,Number of Rear Cameras,Number of Front Cameras,Primary Rear Camera,Primary Front Camera,Memory Card,Extended Memory Available,Extended Memory,OS
0,0,vivo,Vivo V80 5G,62999,84,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster",True,True,True,"Snapdragon 7 Gen4, Octa Core, 2.8 GHz Processor",snapdragon,Snapdragon 7 Gen4,8.0,2.80,"8 GB RAM, 128 GB inbuilt",8.0,128.0,7200,1,90.0,7200 mAh Battery with 90W Fast Charging,"6.59 inches, 1260 x 2750 px, 144 Hz Display with Punch\n Hole",6.59,1260 x 2750,144,50 MP + 50 MP + 8 MP Triple Rear & 50 MP Front Camera,3,1,50.0,50,Memory Card Not Supported,0,NaN,android
1,1,samsung,Samsung Galaxy S25 Ultra,99999,92,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi",True,True,False,"Snapdragon 8 Elite for Galaxy, Octa Core, 4.47 GHz\n Processor",snapdragon,Snapdragon 8 Elite for Galaxy,8.0,4.47,"12 GB RAM, 256 GB inbuilt",12.0,256.0,5000,1,45.0,5000 mAh Battery with 45W Fast Charging,"6.9 inches, 1440 x 3120 px, 120 Hz Display with Punch Hole",6.90,1440 x 3120,120,200 MP Quad Rear & 12 MP Front Camera,4,1,200.0,12,Memory Card Not Supported,0,NaN,android

In [960]:
def fast_charging(integer):

    if integer > 0:
        return integer
    else:
        return np.nan

In [970]:
df1['Fast Charging'].isnull().sum()

np.int64(91)

In [973]:
df1 = df1.drop(columns=[
    'index',
    'SIM',
    'Processor',
    'RAM',
    'Battery',
    'Display',
    'Camera',
    'Memory Card'
])

In [976]:
df1 = df1.drop('Processor Name', axis=1)

In [ ]:
df1.head(2)

,Brand Name,Name,Price,Spec Score,Has 5G,Has NFC,Has IR Blaster,Processor Brand,Number of Cores,Processor Speed,RAM Capacity,ROM Capacity,Battery Capacity,Fast Charging Available,Fast Charging,Screen Size,Resolution,Refresh Rate,Number of Rear Cameras,Number of Front Cameras,Primary Rear Camera,Primary Front Camera,Extended Memory Available,Extended Memory,OS
0,vivo,Vivo V80 5G,62999,84,True,True,True,snapdragon,8.0,2.80,8.0,128.0,7200,1,90.0,6.59,1260 x 2750,144,3,1,50.0,50,0,NaN,android
1,samsung,Samsung Galaxy S25 Ultra,99999,92,True,True,False,snapdragon,8.0,4.47,12.0,256.0,5000,1,45.0,6.90,1440 x 3120,120,4,1,200.0,12,0,NaN,android

In [979]:
df1.shape

(923, 25)

In [1024]:
df1['Primary Front Camera'].value_counts()

Primary Front Camera
8       187
32      160
16      132
50      105
5        89
13       67
12       63
20       36
10       30
18       19
0         8
42        7
10.5      6
12        4
4         3
2         2
10.8      2
7         2
40        1
Name: count, dtype: int64

In [1020]:
temp_df = df1[df1['Primary Front Camera'] == 'Main']

In [1023]:
df1.loc[temp_df.index,'Primary Front Camera'] = '5'

In [1025]:
df1['Primary Front Camera'] = df1['Primary Front Camera'].astype(float)

In [1026]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 923 entries, 0 to 922
Data columns (total 25 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Brand Name                 923 non-null    object
 1   Name                       923 non-null    object
 2   Price                      923 non-null    int64
 3   Spec Score                 923 non-null    int64
 4   Has 5G                     923 non-null    bool
 5   Has NFC                    923 non-null    bool
 6   Has IR Blaster             923 non-null    bool
 7   Processor Brand            923 non-null    object
 8   Number of Cores            923 non-null    float64
 9   Processor Speed            856 non-null    float64
 10  RAM Capacity               923 non-null    float64
 11  ROM Capacity               923 non-null    float64
 12  Battery Capacity           923 non-null    float64
 13  Fast Charging Available    923 non-null    int64
 14  Fast Charging              832 non-null    float64
 15  Screen Size                923 non-null    float64
 16  Resolution                 923 non-null    object
 17  Refresh Rate               923 non-null    int64
 18  Number of Rear Cameras     923 non-null    int64
 19  Number of Front Cameras    923 non-null    int64
 20  Primary Rear Camera        923 non-null    float64
 21  Primary Front Camera       923 non-null    float64
 22  Extended Memory Available  923 non-null    int64
 23  Extended Memory            328 non-null    float64
 24  OS                         923 non-null    object
dtypes: bool(3), float64(10), int64(7), object(5)
memory usage: 161.5+ KB

In [1028]:
df1.to_csv('smartphones_cleaned.csv',index=False)

In [1034]:
df1.loc[df1['Extended Memory Available'] == 0,'Extended Memory'] = 0

In [1036]:
df1.loc[df1['Fast Charging Available'] == 0,'Fast Charging'] = 0

In [1041]:
df1['Extended Memory Available'].value_counts()

Extended Memory Available
0    485
1    438
Name: count, dtype: int64

In [1040]:
df1['Extended Memory'].value_counts()

Extended Memory
0.0      485
1.0      168
2.0      114
512.0     14
256.0     12
128.0     10
1.5        9
64.0       1
Name: count, dtype: int64

In [1039]:
df1['Fast Charging'].value_counts()

Fast Charging
45.0     150
80.0     115
25.0     108
15.0      63
33.0      60
90.0      47
18.0      46
44.0      44
67.0      32
100.0     29
0.0       28
30.0      26
120.0     23
10.0      23
60.0      15
68.0      12
65.0      11
50.0       8
66.0       8
20.0       5
125.0      2
23.0       2
27.0       1
37.0       1
150.0      1
Name: count, dtype: int64

In [1043]:
df1.isna().sum().sort_values(ascending=False)

Extended Memory              110
Processor Speed               67
Fast Charging                 63
Name                           0
Has 5G                         0
Has NFC                        0
Price                          0
Spec Score                     0
Brand Name                     0
Number of Cores                0
Processor Brand                0
Has IR Blaster                 0
ROM Capacity                   0
Battery Capacity               0
Fast Charging Available        0
Screen Size                    0
RAM Capacity                   0
Resolution                     0
Refresh Rate                   0
Number of Front Cameras        0
Number of Rear Cameras         0
Primary Rear Camera            0
Primary Front Camera           0
Extended Memory Available      0
OS                             0
dtype: int64

In [1044]:
df1.duplicated().sum()

np.int64(0)

In [1042]:
df1.to_csv('smartphones_cleaned.csv',index=False)